### ISSUE TITLE
Write some natural language queries to later translate to SPARQL

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#14]
e.g., "What are all of the top-level mental disorders?"

**Comment by anirudh4792** [comment]
I am preparing a list of questions different stakeholders may ask while navigating the platform and I would try to configure them as natural language queries to later translate to SPARQL

**Comment by shnizzedy** [comment]
> [natural language queries/sparql queries in theory](https://docs.google.com/document/d/137eddsH4Dw4KvhoSS4h55LcvlDftDuE1rsMhbvWsBCk/edit)

— @anirudh4792

**Comment by shnizzedy** [comment]
It might be easier to manage if we have each query in its own `.rq` file rather than all in one Gdoc. I set up a [queries branch](https://github.com/ChildMindInstitute/mhdb/tree/queries/queries) to work in.

Here is [a branching tutorial](https://learngitbranching.js.org/) and [Git cheatsheet](https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf)

**Comment by binarybottle** [comment]
Copying from @anirudh4792's gdoc:

Good Researcher

1)  Give me all objectives methods to measure mental/psychological state or bodily state/bodily condition

Input: mental/psychological state or bodily state/bodily condition
Output: mental/psychological state linked to different objective measures/trains of thought

2) I want to collaborate to write a grant. Give me all mhealth people associated with this behaviour

Input: any behaviour that is clickable with a URI/Definition (eg cognition)
Output: sliwinsky’s team

Publish or Perish researcher
Give me all pubmed references/citations to this app 

Clinicians
1)  How can I monitor symptom/mental/psychological state with this dimension subjectively with questions and objectively with apps?
Input: intensity of anger
Output: questions linked to symptom and suggestions to app (our react-native click click app) that where you could load these questions

2) What tasks can I use to measure mental state?
Input: Attention
Output: Tasks to measure attention (Cog Atlas)

Parent
News articles on ‘fixated interests’
What free apps are there for fixated interests (no labels - so no queries like free apps for autism)

**Comment by binarybottle** [comment]
I have created a document of natural language "Planned queries" on our wiki that systematically covers primary pairwise topic areas in the database:  https://github.com/ChildMindInstitute/mhdb/wiki/Planned-queries
