### ISSUE TITLE
A2 hosting

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#20]
Let's try it!

[Ontofox](http://ontofox.hegroup.org/) uses a [Virtuoso](http://vos.openlinksw.com/owiki/wiki/VOS/VOSMake#Build%20Recipe) backend.

[Wikidata](https://query.wikidata.org/) uses a [BlazeGraph](https://wiki.blazegraph.com/wiki/index.php?title=%C3%91%C3%B6%C3%BF.......1800...7909186_hp_printer_$@$$@$_hp_printer_phone_number..YH....hp_printer_contact_number....&oldid=13486) backend.

**Comment by binarybottle** [comment]
A2 hosting set up for ssh:
ssh -p 7822 root@68.66.205.123 
(soon mentalhealth.io)

Need to install blazegraph / virtuoso...

**Comment by binarybottle** [comment]
blazegraph.jar is on the VPS but Java needs to be installed before running "java jar blazegraph.jar".
