### ISSUE TITLE
try Virtuoso

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#21]
[Ontofox](http://ontofox.hegroup.org/) uses a [Virtuoso](http://vos.openlinksw.com/owiki/wiki/VOS/VOSMake#Build%20Recipe) backend.

**Comment by binarybottle** [comment]
Do we still care to try out Virtuoso, or have we moved on?

**Comment by shnizzedy** [comment]
I think Virtuoso is still worth trying but is not a priority (hence this issue being marked an "enhancement"). If you want to abandon it until we hit a wall with Blazegraph, though, we can close this issue.

**Comment by binarybottle** [comment]
Let's reopen when Blazegraph becomes an issue...
