### ISSUE TITLE
name of entity "measures"

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#23]
Would "metrics" be better? Something else?

[![](https://api.gh-polls.com/poll/01BV78D3W9YX5J9D6ZP7HC1W1Y/measures)](https://api.gh-polls.com/poll/01BV78D3W9YX5J9D6ZP7HC1W1Y/measures/vote)
[![](https://api.gh-polls.com/poll/01BV78D3W9YX5J9D6ZP7HC1W1Y/metrics)](https://api.gh-polls.com/poll/01BV78D3W9YX5J9D6ZP7HC1W1Y/metrics/vote)
[![](https://api.gh-polls.com/poll/01BV78D3W9YX5J9D6ZP7HC1W1Y/%5Bsomething%20else%5D)](https://api.gh-polls.com/poll/01BV78D3W9YX5J9D6ZP7HC1W1Y/%5Bsomething%20else%5D/vote)

**Comment by binarybottle** [comment]
"metric" has too specific a definition.

**Comment by shnizzedy** [comment]
Wiktionary has 3 definitions for '[metric](https://en.wiktionary.org/wiki/metric#Noun)' and 23 for '[measure](https://en.wiktionary.org/wiki/measure#Noun)':

[*metric*](https://en.wiktionary.org/wiki/metric#Noun)
1. A measure for something; a means of deriving a quantitative measurement or approximation for otherwise qualitative phenomena (especially used in engineering).[ . . .]
2. (*mathematics*) A measurement of the "distance" between two points in some metric space: it is a real-valued function d(x,y) between points x and y satisfying the following properties: (1) "positive definiteness"[. . .], (2) "symmetry"[. . .], and (3) "triangle inequality".[. . .]
3. *Abbreviation of* metric system.
-----
[*measure*](https://en.wiktionary.org/wiki/measure#Noun)
1. A prescribed quantity or extent.
  1.1. (*obsolete*) Moderation, temperance. [13th-19th c.][. . .]
  1.2. A limit that cannot be exceeded; a bound. (Now chiefly in set phrases.) [from 14th c.][. . .]
  1.3. An (unspecified) portion or quantity. [from 16th c.][. . .]
2. The act or result of measuring.
  2.1. (*now chiefly cooking*) A receptacle or vessel of a standard size, capacity etc. as used to deal out specific quantities of some substance. [from 14th c.]
  2.2. A standard against which something can be judged; a criterion. [from 14th c.][. . .]
  2.3. Any of various standard units of capacity. [from 14th c.][. . .]
  2.4. A unit of measurement. [from 14th c.][. . .]
  2.5. The size of someone or something, as ascertained by measuring. (Now chiefly in *make to measure.*) [from 14th c.][. . .]
  2.6. (*now rare*) The act or process of measuring. [from 14th c.][. . .]
  2.7. A ruler, measuring stick, or graduated tape used to take measurements. [from 16th c.][. . .]
  2.8. (*mathematics, now rare*) A number which is contained in a given number a number of times without a remainder; a divisor or factor. [from 16th c.][. . .]
  2.9. (*geology*) A bed or stratum. [from 17th c.][. . .]
  2.10. (*mathematics*) A function that assigns a non-negative number to a given set following the mathematical nature that is common among length, volume, probability and the like. [from 20th c.][. . .]
3. Metrical rhythm.
  3.1. (*now archaic*) A melody. [from 14th c.]
  3.2. (*now archaic*) A dance. [from 15th c.][. . .]
  3.3. (*poetry*) The manner of ordering and combining the quantities, or long and short syllables; meter; rhythm; hence, a metrical foot. [from 15th c.][. . .]
  3.4. (*music*) A musical designation consisting of all notes and or rests delineated by two vertical bars; an equal and regular division of the whole of a composition; a bar. [from 17th c.]
4. A course of action.
  4.1. (*in the plural*) Actions designed to achieve some purpose; plans. [from 17th c.]
  4.2. A piece of legislation. [from 18th c.] 
-----
Do any of these fit the bill for what we're grouping? I like second general definition of 'measure', but it's the *second* general definition of 4 and has 10 more specific flavors. Is the "otherwise qualitative phenomena" the part that's too specific for metric? And do any of these definitions fit our needs? Maybe we need an altogether different option?

**Comment by anirudh4792** [comment]
I like the first definition for 'metric' for something like reciprocity or
nervousness as it is indirectly measurable (deriving a quantitative
measurement or approximation for otherwise qualitative phenomena) while the
others dont seem to fit perfectly.

Im going to have a look at these later. Jon - they may be worth a quick look
http://www.semantic-web-journal.net/sites/default/files/swj177_7.pdf
https://github.com/inspire-eu-rdf/inspire-rdf-guidelines/issues/10

**Comment by anirudh4792** [comment]
this looks quite close from your other source as they have mentioned
attribute
https://github.com/ChildMindInstitute/mhdb/wiki/Definitions

**Comment by shnizzedy** [comment]
"[Quantity](http://jcgm.bipm.org/vim/en/1.1.html)"?

> property of a phenomenon, body, or substance, where the property has a magnitude that can be expressed as a number and a reference

**Comment by shnizzedy** [comment]
"[Physical Characteristic](http://ecoinformatics.org/oboe/oboe.1.0/oboe-core.owl#PhysicalCharacteristic)"?

> A Physical Characteristic of an Entity is one that is measurable within the physical world, and subsumes primary and derived physical dimensions (e.g., length, mass, area, density). The measured value assigned to a Physical characteristic may be a quantity (a numerical value) or a quality (a label).

**Comment by binarybottle** [comment]
I like that @anirudh4792 highlighted how "metric" can be used to derive "a quantitative
measurement or approximation for otherwise qualitative phenomena".  However, for those who think of the three properties of a metric, the triangle inequality may not be met in most of our cases.  I would go for "quantity" since we are interested in exactly that -- not a means of measurement but the measurement itself, an amount or degree of something, whether that something is a quantitative phenomenon or is derived from a qualitative phenomenon.

**Comment by binarybottle** [comment]
Are we happy with "measure" now that we are using it specifically for signs?

**Comment by shnizzedy** [comment]
I think so.
