### ISSUE TITLE
Updated outline for the mental health platform - general format and for questions

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#24]
The outline - part deux
https://docs.google.com/document/d/1NPlCUA9cCoN2G3ISXlz0lfin9Ljc3fcfb6XmfHoqjPU/edit

**Comment by anirudh4792** [comment]
Add points on what needs to be done/why a bullet has not been done, hurdles faced, add deadlines and assign tasks to team members

**Comment by anirudh4792** [comment]
Anirudh coding tasks - send code to the team for review referencing the task from the outline

**Comment by anirudh4792** [comment]
Merge Jon's milestones and issues into the outline - part deux

**Comment by binarybottle** [comment]
This issue references outside documents and is not self-contained.  Please define the issue or close.
