### ISSUE TITLE
Example discussed with Jon

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#25]
> Example discussed with Jon (took time with Google draw)
[![almond example](https://user-images.githubusercontent.com/5974438/31241704-c1692b76-a9d2-11e7-829c-f5e34f4fa096.png)](https://docs.google.com/drawings/d/1f2wSEcsIcTsZloNBORSgmsLP--zacj-eZ4njqnBfXoA/edit?usp=sharing)

— @anirudh4792

**Comment by shnizzedy** [comment]
In [the same document](https://docs.google.com/drawings/d/1f2wSEcsIcTsZloNBORSgmsLP--zacj-eZ4njqnBfXoA/edit?usp=sharing), I drew how I would map the same end-to-end relationship:

![almond example 1](https://user-images.githubusercontent.com/5974438/31241797-05529430-a9d3-11e7-99e0-ecfb34153e0b.png)

Main points of difference:

- **unlabeled directional edges vs. labeled undirectional edges.** Directional labeled edges might be best, but I think the direction of each relationship is clear from the labels.
- **semantic grouping.** Are your boxes reiterating your color-coding? Some of these relationships are more complicated than what we've encoded so far. We could further relate the blank `_algorithm` nodes, but I think just grouping algorithms and measures is specific enough for the kinds of questions we'll be asking.

**Comment by shnizzedy** [comment]
@anirudh4792, thanks for taking the time and making a diagram. I had a much easier time interpreting and critiquing the diagram than I did with the spreadsheet.

**Comment by binarybottle** [comment]
I recommend editing the title to be more descriptive for future searches.
