### ISSUE TITLE
And reciprocity also linked to mhealth people!

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#26]
> And reciprocity also linked to mhealth people! [Jonhwang](https://github.com/shnizzedy) – need to be constructed carefully as we don’t want all information to be pulled up along train of thought if two components are indirectly related by five intermediaries

— @anirudh4792

**Comment by shnizzedy** [comment]
It's true that these relationships need to be constructed carefully, but my point here was that our questions need to be more specific than "give me all `x` related to `y`"; we have to care *how* things are related.

**Comment by binarybottle** [comment]
I don't understand what this issue is about.  Please clarify and resolve.

**Comment by shnizzedy** [comment]
being resolved in #53 and #54
