### ISSUE TITLE
‘neutral behaviours’

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#27]
I don't dislike the term, I just think it's not inclusive of all the nouns & neutral derivations you're compiling, i.e., I am not convinced that "being alone" or "fixated interests" or "repeated compulsive thoughts" are behaviors.

We should either find a term that fits every item of that type or restrict inclusion or reframe some phrases ("seeking solitude", "fixating on interests", "acting or compulsive thoughts") if we are certain behaviors is the right term for what we want.

**Comment by anirudh4792** [comment]
Appreciate the feedback - thank you. I think we should do both. Your phrasing is exactly what I was hoping to do and is really good for 1 and 2. Let me give this more thought, try to get interesting examples, explore possible structures and get back to you. Would it not be a good thing to not have a uniform fixed structure (I feel some conform to some structures better than the other)

**Comment by shnizzedy** [comment]
I completely agree that we should "not have a uniform fixed structure [. . . if] some conform to some structures better than the other". We should just be sure to be clear about what structures we are using and when.

**Comment by shnizzedy** [comment]
> Hello Arno,
>
> I have been conceptualizing the system and questionnaire (could explain in detail tomorrow). After huffing and puffing, here is an example https://docs.google.com/spreadsheets/d/1k2RkEpatNZKtA4O3-4NYh7nV9bDdPHxHp9w19iC6rpY/edit?usp=sharing
>
> I could act on your feedback and have something more concrete with more examples for tomorrow.
>
> Additionally, here are some nice visuals we could use for the online questionnaire https://www.16personalities.com/country-profiles/japan

— @anirudh4792 

> Thanks, Anirudh.
> 
> frequency - regular vs. often/good doesn't make sense to me.
> 
> Have Jon take a look.
> 
> Cheers, @rno

— @binarybottle 

You know I'm confused by the format, but leaving that aside:

1. Is the idea here to
  a. link these symptoms to these questions to E-SWAN questions to these neutral behaviors
  b. reduce/combine symptoms to these neutral behaviors and link these to these questions and E-SWAN questions
  or
  c. something else?
2. duration / frequency / capability: these are hard to nail down neutral scales for. I'd try
  a. duration: very short < short < **typical** < long < very long
  b. frequency: never < rarely < **sometimes** < often < always
  c. capability:
    1. **is unable to** < **is able to with difficulty** < **is able to** < **is able to easily** < **is unable to not**
    or
    2. **cannot** < **can with difficulty** < **can** < **can easily** < **cannot not**
  (For capability, I think the extreme on the positive end should be the polar opposite of inability.)
3. past / current: each of these should be more specific, and should apply to each facet, no? I'm unclear on how specific or open-ended these are intended to be.
4. Other's perception of your behaviour: Is the question here "Has anyone spoken to you specifically about _x_ behavior?"? Is that kind of question represented in the existing questionnaires? I think a better approach would be to ask the other questions (3rd person versions of the 1st person questions) to teachers, parents, peers, etc.

**Comment by shnizzedy** [comment]
> Thank you. I’ve made some changes. Feels like back to square one – How to generate questions from symptoms and I am having trouble generating them.
> 
> One path could be to zoom out a bit, have attention as the neutral behaviour and have several symptoms and questions mapped to it, adding context as a dimension. This approach seems feasible and possibly a little programmatic as we would have around 50-100 core ‘neutral behaviours’.
> 
> Right now, we are trying to get 1000 neutral behaviours (from every symptom). I could generate an example for the above.
> 
> Note: We are going more levels deeper than E-SWAN which tackles only 1 dimension and is faithful to the DSM vs actually generating behaviours. They also select only a subset of symptoms in ADHD
> 
> But I have suggestions on points like one person’s pretty much is another person’s very much and how to overcome these uncertainties.

— @anirudh4792 

I _really_ like the idea of abstracting to "around 50–100 core ‘neutral behaviours’."

**Comment by anirudh4792** [comment]
Thanks Jon!
0) Forget the format for now - it is simply for illustrative purposes
1) E-SWAN is only there just for comparison and to know what they did. The questions from questionnaires were also there just to give you an idea of whats out there in that component. The main aim here is to generate questions, add dimensions to 'neutral behaviours' while keeping in mind how a parent could answer the question (hence, the follow up questions). Subsequently, these questions will be mapped to symptoms, objective measures etc. later in the grand scheme of things
 2) is exactly what I was looking for and seems appropriate - just awesome (there is no charge for awesomeness)

**Comment by binarybottle** [comment]
- 2c. cannot < can with difficulty < can < can easily < cannot avoid [doing] OR must [do]

- intensity?:  
    no effect < mild < severe
    opposite effect < mildly opposing response < no effect < mild effect < severe

- reaction?:  
    no reaction < mild < severe
    severe opposite reaction < mild opposing reaction < none < mild < severe

**Comment by anirudh4792** [comment]
a. duration: very short < short < typical < long < very long eg: sustaining attention
b. frequency: never < rarely < sometimes < often < always eg: running or climbing when inappropriate
c. ability: cannot < can with difficulty < can < can easily < cannot avoid [doing] OR must [do] eg: following through on instructions
d. opposite effect < mildly opposing response < no effect < mild effect < severe
e.  REACTION severe opposite reaction < mild opposing reaction < none < mild < severe eg: anticipating social situations, fear of doing something that will lead to embarrassment

However, I feel attention to detail does not fit these (interestingly, one end of the scale for this is considered poor for adhd while other end is considered 'poor/great' for adhd (hyper focus, extreme attention to detail). A very good/bad seemed to fit). There are other examples with similar polarities.

I also tried combining dimensions and it was a mess in my head (can never sustain attention for long etc.)

**Comment by binarybottle** [comment]
attention to detail:
a. very short to very long attention span
b. never attend to anything to always attending to something
c. cannot sustain attention to cannot stop attending to things
d. attend to everything but what I should (distracted) to cannot attend to anything but center of focus
e. (same as d when presented with stimuli or when directed by another)

**Comment by anirudh4792** [comment]
more examples like attention to detail
https://docs.google.com/document/d/15P-Hr2vq_HyJlcZZzWgidzqb9yJmIikwmHYWpdccLs8/edit

**Comment by shnizzedy** [comment]
I wrote specific comments and suggestions in the document.

Generally, we need to be careful about which part of a complex behavior we are modifying.
E.g., for _attention to detail_ are we interested in the duration, frequency, intensity, etc. of the _attention_ or of the _detail_? For _sharing of emotions_, the duration, frequency, intensity, etc. of the _sharing_ or of the _emotions_? For _being exposed to scrutiny in social situations_, the duration, frequency, intensity, etc. of _being in social situations_, of _being exposed to scrutiny_, of the _social situations_ or of the _scrutiny_?

In that last example, should _in social situations_ be a modifier? I know we've talked about having a vocabulary of contexts to apply to decontextualized behaviors.

The "(same as _x_)" examples give me pause. Are these dimensions sometimes interchangeable?

**Comment by shnizzedy** [comment]
@binarybottle, in [your _attention to detail_ example above](https://github.com/ChildMindInstitute/mhdb/issues/27#issuecomment-335637636)
> attention to detail:
> a. very short to very long attention span
> b. never attend to anything to always attending to something
> c. cannot sustain attention to cannot stop attending to things
> d. attend to everything but what I should (distracted) to cannot attend to anything but center of focus
> e. (same as d when presented with stimuli or when directed by another)

, I see how these phrases deal with _attention_ but don't see how they relate _to detail_.

**Comment by binarybottle** [comment]
a. duration: very short < short < typical < long < very long eg: sustaining attention
b. frequency: never < rarely < sometimes < often < always eg: running or climbing when inappropriate
c. ability: cannot < can with difficulty < can < can easily < cannot avoid [doing] OR must [do]
d. intensity: opposite effect < mildly opposing response < no effect < mild effect < severe
e. consistency
f. specificity

attention to detail:
a. attends to detail for very short to very long periods
    For fun, let's include duration of opposite behavior X, 
    where X is "maintains inattention" or "attends to non-detailed generalities":
    - X for very long periods vs. attends to detail for very long periods
    - X for very long periods vs. X for very short periods
    - attends to detail for very short periods vs. X for very short periods
b. never attends to detail -> always attends to details
c. cannot attend to details -> must attend to details
d. attend to everything but details -> attends only to details
e: randomly attends to details (or attends to random details) -> attends to all details
f1. attends to certain details -> attends to all details (or attends to random details)
f2. attends to details under certain conditions -> attends to details under all conditions

**Comment by anirudh4792** [comment]
https://docs.google.com/document/d/1h87oNlDdKiwThbISvX0RcjUgp742GjEM5SqwnB1SBqI/edit?usp=sharing

More examples with different types of consistency/specificity

Will incorporate jon's comments after we discuss them for a to d.

**Comment by binarybottle** [comment]
@anirudh4792 -- linking out to google docs ensures that this information will be lost in the future.  best to keep these discussions succinct within github until the issue is resolved, and then expand our efforts in other formats/venues...

**Comment by anirudh4792** [comment]
Yes. But we cant add comments on github
More examples with different types of consistency/specificity
key:
 e. consistency
f. specificity

1) Being accurate in work or activities
e. Is randomly accurate in work -> accurate in all work
f1. Accurate in certain types of work -> accurate in all types of work
f2. accurate in work under certain conditions -> accurate in work under all conditions

2) Sustaining attention
e. randomly sustains attention (or sustains attentions randomly) ->  always sustains attention (sustains attention always)
f. Sustains attention under certain conditions ->  sustains attention under all conditions

3) Being exposed to scrutiny in social situations
e1. rarely exposed to scrutiny -> consistently exposed to scrutiny in social situations
e2. Reacts randomly when exposed to scrutiny -> reacts consistently when exposed to scrutiny
f2. exposed to scrutiny under certain social situations-> exposed to scrutiny under all social situations

4) Sharing of emotions
e. shares all emotions at same intensity -> shares different emotions at different intensity
f1. shares certain types of emotions -> shares all types of emotions
f2. shares emotions under certain conditions -> shares emotions under all conditions

5) Reaction to sensory stimuli
e. Always reacts to sensory stimuli at same intensity -> reacts differently to sensory stimuli at different intensity
f1. Reacts to certain types of sensory stimuli  -> Reacts to certain types of sensory stimuli
f2. Reacts to sensory stimuli under certain conditions -> reacts to sensory stimuli under all conditions

6) behaviours performed repeatedly without a seeming purpose <opens and closes doors, switches lights on and of, lines up toys or objects>
e. Repeats certain types of behaviours with different consistency -> Repeats different behaviours with same consistency
f2. Repeats behaviours under certain conditions -> repeats behaviours under all conditions

**Comment by anirudh4792** [comment]
Wrapped my head around this too much. 

Behaviour = attention to details, dimension = duration
Let attention = A (verb) and details = B (noun), let dimension lower limit = X (short) and dimension upper limit = Y (long)

From possibilities of 4! = 12 to 4!/2 = 6

On Jon’s earlier comment, I feel only the opposite behaviour of the verb (not having attention/inattention) should be taken. Opposite nouns are valid only in rare cases and if so, it should be taken as a separate behaviour (eg response to sensory stimuli vs response to non-sensory stimuli)

Why opposite behaviours:
In autism, children pay attention to detail to objects of interest and do not even look at other objects (this is not reflected by pays attention to detail only for a short time but by does not pay attention for long time (does not pay attention even for a short time - boo for the english language)

I like what Arno did to ability (cannot < can with difficulty < can < can easily < cannot avoid [doing] OR must [do]). I have not seen this (cannot to can do too much/cannot stop) in any questionnaire.

My preference is for all our dimensions to have this

Possible combinations (A,B); (A, B-opposite); (A-opposite, B); (A-opposite, B-opposite)
We select only (A,B); (A-opposite, B);
Let (A,B) = N and (A-opposite, B) = N-opposite

The winner (N-opposite, Y) : (N, Y)
Having inattention to details for very long vs having attention to detail for very long
As it contains within it (N, X) : (N, Y) and (N-opposite, X) : (N-opposite, Y)
with (N-opposite, Y) sometimes similar but subtly different to (N, X)
and (N, Y) sometimes similar but subtly different to (N-opposite, X)

I was thinking something like a circle rather than a linear scale to account for these subtleties. 

2) Consistency and specificity 
f1. attends to certain details -> attends to all details (or attends to random details)
Applying opposite behavior < mildly opposite behavior < mild behavior < good behavior < severe behavior
Implies
Does not attend to any details (eg in all objects of disinterest) < does not attend to some details (ADHD forgets cc’ing people in emails) < does attend to some details  < does attend to all details < does not stop attending to all details (keeps staring at the object of interest)

Coming soon
Layer 3 (time) + Layer 2 (consistency, specificity) + Layer 1 (duration, frequency, intensity)

**Comment by binarybottle** [comment]
I follow and agree with everything in your previous comment up to the "good behavior", which sounds judgmental.  I also don't know why you would need a Layer 3 (time) when consistency directly deals with time.

**Comment by anirudh4792** [comment]
What "good behavior" meant in this case was having "good attention to detail" but I agree the wording needs to be changed.

Ive been thinking a lot about this and I feel an 'about average' option should be present (I imagined asking people what your child's attention to detail is and I felt many possible answers could be 'just regular/normal' and does not stand out as inattentive or highly attentive but is not represented by mild behavior/attends to some details).

Also, f1. was imbalanced. Here is a new version for consistency and specificity (I have tried to combine both consistency and specificity which may not be the best option)

Applying opposite behavior < mildly opposite behavior < behavior is uniform in consistency across different situations < mild behavior < severe behavior
Implies
Does not attend to any details (eg in all objects of disinterest) < does not attend to some details (ADHD forgets cc’ing people in emails) < attends to detail consistently across different situations < does attend to all details < does not stop attending to all details (keeps staring at the object of interest)

I felt Layer 3 (time) was needed to observe trends in different time periods (eg month 1 vs month 2, last 2 months vs last 8 months etc.). Consistency dealt with performing a behavior under different specifications within a specific time period (eg he performed this behavior more on tuesdays and fridays;  the behavior was more intense outside home (eg SM).

I think consistency and specificity go hand in hand and I agree that consistency could be taken as a sub-type of Layer 3.

**Comment by binarybottle** [comment]
Let's consider the kinds of questions we might ask:
![questionnaire flowchart](https://user-images.githubusercontent.com/236532/31746010-342aea4a-b433-11e7-9bbc-14453881aecf.png)

https://docs.google.com/drawings/d/1VhDkEtkBqwFGqUC_eC_6moYhmRZ5MzWDgkBHfF_TtgU/edit?usp=sharing

**Comment by anirudh4792** [comment]
Awesome. Thank you. Was typing away but will try to communicate by graphical diagrams vs long text henceforth :)

**Comment by anirudh4792** [comment]
Integrating Arno's flowchart with list of behaviors grouped under 'Attention' (All modifications have been underlined).
https://docs.google.com/drawings/d/1hPHY_1uuk4oVPS1u-8Bx100-7JgEYjH61EIIf2ZL4Dw/edit?usp=sharing

I have added 'does not try' as an option under ability (does not try to do homework is different from cannot do homework)

I have added questions under dimensions when applicable (eg How is your attention span or how long can you sustain attention)

For neutral behaviors that could not be added, I have created a table and added them as implications. 

Ultimately, I would like for parents to be able to identify and act/keep track of strengths and weaknesses and I have tried to include this concept.

**Comment by binarybottle** [comment]
I think that the table we need to create is one that tries to map the different "implications" of attention to the different dimensions (duration, intensity, frequency, context dependency) to see if we can reduce the number of questions that need to be posed.  

Also, I would replace 'does not try' with simply 'does not', and I believe this is covered by frequency: 'never'.

**Comment by anirudh4792** [comment]
The issue of implications has been solved in issue #30 
I agree that does not try/does not is covered in frequency and I have removed it (we have other such instances as well)

Updated example for attention
https://docs.google.com/drawings/d/1LKlTR9LCxHQciXMyQCPyAr3Ap0DDVCXXkVgAHS2wUXk/edit?usp=sharing

example for non communicative behaviors (google draw was bad)
https://docs.google.com/drawings/d/1fydATax1Q63THY9Yaew16DBr_rHMsVdSTH09cWnJJs4/edit?usp=sharing

**Comment by binarybottle** [comment]
The updated example for attention looks good.  This will probably be one of the simplest cases, with a single symptom (attention to detail) for a category (attention), with all other symptoms (limited attention span) subsumed within the category's dimensions (duration).

Regarding non-communicative behaviors:
1. We need to use more intuitive language.
2. We should differentiate doing/expressing and receiving/understanding.

**Comment by anirudh4792** [comment]
Agree to both. I have followed this format and order (I shall continue to give more examples using the following code than google draw)
Scenario 1) E - subsumed neutral behaviors as **examples** of core neutral behaviors if applicable as the prefix to the neutral behavior was indicated in the questions
eg social use of eye contact - eye contact
use and understanding of body postures - body postures
use and understanding of gestures <pointing, waving, nodding, shaking head> - gestures
Scenario 2) S - **subsumed** within the category's dimensions
Scenario 3) C - symptom (eg attention to detail) for a category (eg attention) get their own dimensions

**Comment by binarybottle** [comment]
The three scenarios sound reasonable.  Let's just not lose the verbs (use, understand,...).

**Comment by anirudh4792** [comment]
220 neutral behaviors transformed into questions using the above scenarios, but presented in a more readable and structured format (didnt use the letter code)

- Every neutral behavior was included either as an example, dimension or core neutral/parent behavior

- Justification of decisions, links to other categories, insights added as comments (in a format understandable to me) to explain during our next meeting)

https://docs.google.com/document/d/19at5dngbUS1Jt4K_Z5laq-Y7fSB8UeNJsPawIQ6BOi4/edit?usp=sharing

**Comment by shnizzedy** [comment]
I like the direction this is going. A lot of these are questions that make me want to take the questionnaire / play the game!

**Comment by shnizzedy** [comment]
I scrolled through the core behaviors and took a stab at putting them in a tree:

[![core neutral behaviors - page 1](https://user-images.githubusercontent.com/5974438/31912327-7b2a76c2-b811-11e7-99d6-45ef285df5d3.png)](https://www.lucidchart.com/invitations/accept/7452800b-12bd-4daa-aa51-203513669b0d)

Letting [LucidChart](https://www.lucidchart.com/invitations/accept/7452800b-12bd-4daa-aa51-203513669b0d) rearrange a hierarchy based on the relationships I defined gives us some interesting levels:

[![core neutral behaviors - page 1 1](https://user-images.githubusercontent.com/5974438/31912385-b99bdf68-b811-11e7-99a8-960ddbc89bfe.png)](https://www.lucidchart.com/invitations/accept/7452800b-12bd-4daa-aa51-203513669b0d)

I'm curious if we can draw meaningful groupings among these entities. I'm not sure if any one of these entities, particularly 'controlling urges', is in the right place. I'm curious what you guys think.

**Comment by anirudh4792** [comment]
Just wow. Thank you very much for the effort.

Overall, I thought the groupings made sense - was very logical to me. Only suggestion - for 'controlling urges', I feel is not an implication of impulsiveness, repetitive behaviors  or interests but indulgence in urges (for the sake of neutrality) could be their cause.
Also, impulsivity could also be linked to activity

I particularly liked

- Understanding nonverbal comm behaviors leads to using them which leads to social communication

- How fear has been linked to accepting change, anticipation of social situations and bodily changes

- How the 'ADHD' part has been logically presented. Attention and activity leads to implications in hyperactivity and impulsivity. 

very cool

**Comment by binarybottle** [comment]
Great job, Jon!  I really like the organization of this chart!  I think that we should put this in a form soon for evaluation by clinicians.  Clearly not just show and ask "What do you think?" but more along the lines of pairing different items and asking about the strength of their relationships...

**Comment by anirudh4792** [comment]
Thank you Arno for the suggestion to look into patterns (among families and across families at the same levels (eg across core parent behaviors or level 1 sub-behaviors)
[Inherent structure and patterns in dimensions](https://docs.google.com/document/d/1dVVFtWV1hL2nB0g34M4fGBQr8jCoMwWV7_wbpOFibPM/edit)

Insights

1) It is evident that we could merge ability and intensity into one as intensity that reflects ability
2) The parent (underlying cause) can cover all possible dimensions while the sub-behaviors/implications can have specific dimensions as the others are already covered in the underlying cause
3) In some cases where only some options on the scale are needed (eg 0-3 rather than 0-5), redundant ones have been converted into opposite behaviors (see google doc with the comment - Arno opp beh)
4) The dimension 'Duration' is inherently present in the familiy external/internal: activity, interests and attention and their sub-behaviors 
5) Jon's structure adds readability by adding/creating parents (these parents have the same structure as their sub-behaviors and we can do the necessary edits to have a format like 2 (eg fear/anticipation has been added as a category while anticipation of social situations becomes a sub-behavior; good move as now we can include/link specific phobias to fear)

Clarification
1) Jon's structure adds readability though activity is the same as hyperactivity (I mislabeled the gdoc; activity encompases hyper and hypo activity)
Response to social situation same as response to non-verbal communicative behaviors

Minor doubt that doesnt warrant typing on github
1) Unable to understand the logic of arrows going into sensory stimuli

**Comment by shnizzedy** [comment]
I removed _hyperactivity_ and added a link from *activity* to *interacting with others*.

![core neutral behaviors - page 1 2](https://user-images.githubusercontent.com/5974438/31966272-2079e312-b8d8-11e7-8d8a-27d0a3187145.png)

---

Re: [1. Unable to understand the logic of arrows going into sensory stimuli](https://github.com/ChildMindInstitute/mhdb/issues/27#issuecomment-338889607), if you're talking about the live LucidChart, I was playing with different organization scheme, hit the free-tier complexity limit, and stopped. I've since reverted to the version in this comment above above.

----

To be able to deal with more complexity, I translated the LucidChart diagram [into TTL](https://drive.google.com/file/d/0B8HQ-XibzsxXckxWZmVOT21WQ2s/view?usp=sharing).

![core](https://user-images.githubusercontent.com/5974438/31966906-392a147a-b8da-11e7-928a-d010e3ac57a4.png)

![image](https://user-images.githubusercontent.com/5974438/31966494-ddc36c90-b8d8-11e7-8098-0c43e73716eb.png)

Annoyingly, I couldn't quickly figure out how to get the chart from LucidChart without manually downloading, so I uploaded [the generated ttl to Google Drive as a txt file](https://drive.google.com/file/d/0B8HQ-XibzsxXckxWZmVOT21WQ2s/view?usp=sharing). There's nothing new in this format besides 
1. the format
2. articulating that the entities are classes
3. no complexity limit
4. we have code to convert directed diagrams from LucidChart to TTL

**Comment by binarybottle** [comment]
Nice work, Jon!

**Comment by anirudh4792** [comment]
Pulled up an old document from Stan. Please see pages 31 to 38. Do you feel they have categorized symptoms well (not based on disorder but on topics like everyday activities)
[BASC-3-Rating-Scales-Report-with-Intervention-Recommendations-Sample.pdf](https://github.com/ChildMindInstitute/mhdb/files/1420264/BASC-3-Rating-Scales-Report-with-Intervention-Recommendations-Sample.pdf)

**Comment by shnizzedy** [comment]
I think they've categorized behaviors rather than symptoms (*BASC* is ***B**ehavior **A**ssessment **S**ystem for **C**hildren*), but I think their groupings are reasonable. I particularly like that the BASC solicits self-, parent-, and teacher-perspective assessments.

**Comment by anirudh4792** [comment]
Sorry. i meant they categorize or group symptoms under core behaviors. @binarybottle see above for Stan's old questionnaire

**Comment by binarybottle** [comment]
I'm not sure what to think when I see the following in BASC:

"Autism Probability
 17. Seems odd. (Never)"

**Comment by anirudh4792** [comment]
This is a manual interpretation report (the user has answered 'never' for behaviors grouped under autism probability
@shnizzedy this is what we would not want to do but I get your point with questioning why we should retaining core behaviors in the questionnaire/response analysis vs just keeping the questions that represent them

Also See issue #37  for comparison of different domains

**Comment by shnizzedy** [comment]
Just to clarify, I've been questioning *if* these "core behaviors" are behaviors or experiences at all, and, if not, what they are (anything besides abstract concepts based on grouping signs, symptoms, behaviors and/or experiences) and what their utility is or can be.

With the example of [`Autism Probability`: `Seems odd.`](https://github.com/ChildMindInstitute/mhdb/issues/27#issuecomment-340079842):

- `Seems odd.` is an articulable experience that can be a valuable source of information. Lots of people fret about how they are perceived and with a BASC-like questionnaire, we can see where perceptions align and where they conflict.
- The only utilities I see in `Autism Probability` are as an entry-point (e.g., someone searching for autism information) and as a means to buy-in (e.g., explaining our questionnaire's coverage). If we were to ask people about the `autism probability` of themselves or others, I suspect we'd get something pretty similar to their answers to `seems odd`, but less directly (i.e., noisier).

My concern here is that we risk enforcing existing models by relying on them to structure our probes. I think a case can be made for some of these "core behaviors", but most of them seem like problematic relics to me.

**Comment by binarybottle** [comment]
I strongly agree with @shnizzedy's last paragraph in his previous comment, and I agree that it would be interesting to see how much self vs. other's perceptions dis/agree with each other.  

Perhaps we could lump internal experience under "mental experience" or "thought" and replace "behavior" with "thought/behavior" in our discussions?

**Comment by shnizzedy** [comment]
I'm not sure if "mental experience", "thought" and "behavior" encompass enough. Do pain, attention or irritability fit any of those categories?

**Comment by anirudh4792** [comment]
I feel pain and irritability come broadly under emotional state and mental
experience.

Attention may fall under cognitive level. I like where this is going in
that we need precise defined unambiguous classifications or none at all?

**Comment by binarybottle** [comment]
This discussion touches on a variety of interesting topics, but are we satisfied with our use of the term "state" and "neutral state" as they apply to "signs" or "symptoms"?  If so, can we close this issue?

**Comment by shnizzedy** [comment]
I think 'state' is better than 'behavior' and is workable.
