### ISSUE TITLE
Categorizing neutral behaviors into core neutral behaviors

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#30]
@binarybottle @shnizzedy Please give me feedback on how this grouping looks to you for 220 symptoms (converted into neutral behaviors) covering autism, adhd, social anxiety, tic and panic disorders
https://docs.google.com/document/d/1nzjYmPaOuIW07c2mGT0FO07WVxu9mw0qyYa6BpnB5Xk/edit
eg **Attention**
having attention to detail
being accurate in work or activities
sustaining attention
listening when spoken to
following through on instructions, completing work
organizing tasks and activities
engaging in tasks requiring sustained mental effort
keeping track of things
getting distracted by extraneous stimuli
remembering things
keeping track of things <school materials, pencils, books, tools, wallets, keys, paperwork, eyeglasses, mobile telephones>

compare the above with https://docs.google.com/drawings/d/1VhDkEtkBqwFGqUC_eC_6moYhmRZ5MzWDgkBHfF_TtgU/edit?usp=sharing

I am trying to include some neutral behaviors within the dimensions (eg attention span is paired with duration in the above example) and others as implications in a spoke-wheel like diagram where users can add implications (eg being accurate in work or activities)

P.S My autism grouping was inspired from https://depts.washington.edu/dbpeds/Screening%20Tools/DSM-5(ASD.Guidelines)Feb2013.pdf - a wonderful resource - we have neutral behaviors for all these

**Comment by binarybottle** [comment]
I'm not sure the following are principally about attention.  That is, we can relate them to attention, but perhaps they would need to be linked to other core facilities/behaviors as well.

- following through on instructions, completing work
- organizing tasks and activities
- keeping track of things
- remembering things

**Comment by anirudh4792** [comment]
Spot on. I could not understand why these were specifically under attention in the DSM which we are moving away from anyway. I think they must be excluded from attention and grouped elsewhere where more appropriate.

This solves issue #27
