### ISSUE TITLE
'neutral behaviors' + 'dimensions' 'enhancing' 'extended' 'E-SWAN' and 'Encompassing' 'CMI General questionnaire'

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#33]
Included neutral behaviors + dimensions for 'Eating', 'Conduct', 'Mood', 'Depression', 'General Anxiety', 'Specific Phobia/Agoraphobia', 'Separation anxiety', 'substance abuse'
https://docs.google.com/document/d/1PDKxWGFZ0QvXJMeFDEX87F6T6u9LXAehAUvYrVnoYXM/edit?usp=sharing

It looks like all the questions in the CMI general questionnaire and E-SWAN have been covered for in the overall structure (examples, dimensions or implications - will explain on Friday). 

I am however not sure if this is the best strategy but I have got many insights: 
eg how to reduce questions (eg I get very easily depressed in intensity is very similar to I always get depressed in frequency; ),
If the user answers yes in the 'level one starting questions for attention - I am incredibly focused', there is no point in asking if he/she always loses focus in frequency in the follow up question

Next steps: I start with Stan's old questionnqire for rating scales/behaviors, and try to connect everyday behaviors (eg sleep, eating, activity levels, schedule/context etc.) overlaying this to emotions/mental states (eg joy, happiness, anger, satisfaction) and overlaying this to neutral behaviors, and overlaying everything with coco-puffs

**Comment by binarybottle** [comment]
It is a very good idea to reduce redundancy in our questions, whether we deem some combination of neutral behavior + dimensions to be redundant with another or we deem a truncated scale to be an appropriate followup to a given question.  

However, first we need to ensure our categories, behaviors, and dimensions are all reasonable.  Then we can spend time compressing the set into what will become adaptive, manageable trajectories of intuitively navigable questions.

PS -- What is "Stan's old questionnaire" in your Next steps?
PPS -- Not cocoa puffs, Anirudh.  Let's be accurate -- Annie's Organic Cocoa Bunnies.
