### ISSUE TITLE
Articulate our model and assumptions

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#34]
Are we working under an "essentialist model of mental disorders, [. . .] a mechanistic property cluster (MPC) model" [(Hoffart & Johnson, 2017)](http://journals.sagepub.com.proxy.wexler.hunter.cuny.edu/doi/full/10.1177/2167702617727096#annotations:0UVRjLpsEeeT8ys3KAxKJA) or some other model?

My inclination is toward an mechanistic property cluster model, in which
> disorders are sets of symptoms connected through a system of causal relations. For instance, in depression, stressful life circumstances may lead to lack of sleep, which, in turn, leads to fatigue, which elicits concentration problems, which, in turn, feed back to and reinforce the sleeping difficulties, and so forth. Thus, symptoms may cause each other and their causal relations explain their co-occurrence; there is no need for postulating an underlying causal disease

— [(Hoffart & Johnson, 2017)](https://hyp.is/S0IwvrpnEeetXzt-C8gsWw/journals.sagepub.com.proxy.wexler.hunter.cuny.edu/doi/full/10.1177/2167702617727096),

as opposed to 
> in the widely used disease model of mental disorders, [in which] mental disorders are considered to be essentialist kinds. Analogous to the structure of somatic diseases (e.g., a virus causing the symptoms of flu), mental problems cluster together in disorders because they are caused by the same underlying process

— [(Hoffart & Johnson, 2017)](https://hyp.is/1GOOMLplEeeqj0fU9fYSPA/journals.sagepub.com.proxy.wexler.hunter.cuny.edu/doi/full/10.1177/2167702617727096).

We need to be careful not to conflate models or else we'll make meaningless assertions because "although reflective constructs such as depression and core conflict can be said to cause observable symptoms in a between-persons sense, it is meaningless to assert that a particular patient’s core conflict or depression caused his/her symptoms" [(Hoffart & Johnson, 2017)](https://hyp.is/3ldYwLpxEeeK07cyURY92g/journals.sagepub.com.proxy.wexler.hunter.cuny.edu/doi/full/10.1177/2167702617727096).

## Reference
Hoffart, A., & Johnson, S. U. (2017). Psychodynamic and Cognitive-Behavioral Therapies Are More Different Than You Think: Conceptualizations of Mental Problems and Consequences for Studying Mechanisms of Change. *Clinical Psychological Science*. [doi:10.1177/2167702617727096](http://journals.sagepub.com.proxy.wexler.hunter.cuny.edu/doi/full/10.1177/2167702617727096)

---

I highlighted the recent *Clinical Psychological Science* article cited above in [Hypothes.is](https://hypothes.is/groups/AkmnpKYE/child-mind-institute-itl) as I read it.

I also created [a group Zotero library](https://www.zotero.org/groups/890036/cmi-itl-database/items/collectionKey/YHTLTM3V/order/year/sort/desc) with some potentially relevant references. A lot of this work has been done already; we should take advantage of these previous efforts.

**Comment by binarybottle** [comment]
I am leaning more toward a mechanistic property cluster model myself, but let's keep it agnostic for the time being.  A graph of defined relations could include relations that are directed or undirected, and could imply either causation or correlation.

**Comment by anirudh4792** [comment]
I feel we were never non-mechanistic to begin with. 
"Thus, symptoms may cause each other and their causal relations explain their co-occurrence; there is no need for postulating an underlying causal disease"
I guess the underlying causal disease here are diagnostic labels or the name of mental health disorders like ADHD causes a, b, c etc. 
Our case focusses on the underlying behavior/core behavior/underlying symptom which branches out into sub-behaviors

**Comment by binarybottle** [comment]
have we settled on non-causal relations?  should we close this issue?
