### ISSUE TITLE
Comparison of Domains - classifying core behaviors into domains

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#37]
First level questions (see issue #36 ) were classified under 
Everyday Activities (eg sleep, eating, energy, overall emotional state etc.);
Mental States/Skills related to the mind _(How I define mind - receives data from the senses and stores memory_)
Bodily Conditions/States; Related to the body
Things related to the intellect/Applying the mind _(How I define intellect - retrieves memory, analyses data from the senses, sends solutions and decisions)_

What are our core behaviors in the questionnaire until now?
Attention, activity, understanding other's emotions, nonverbal communicative behaviors, social skills, sensory stimuli, mood, depression, controlling urges, impulsivity, handling scrutiny/comfort in social situations, social communication, social relationships/interacting with others, preoccupations/obsessions with interests, repetitive behaviors, speech, accepting change, fear in anticipation/thinking about things, separation anxiety, anxiety/generalized anxiety, conduct, substance abuse, sleep, overall emotional state

Our train of thought for sensors and wearables were classified as
(1) mental/bodily state
(2) measurable characteristic of mental/bodily state
(3) quantity to measure
(4) location of measurement
(5) sensor
(6) device (links to information like makers, models, characteristics of device, etc.) 
 originally as 
1) mental/physiological state
2) measurable bodily state/bodily condition
3) physical/chemical property
4) sensor
5) location
6) tech /wearable/app/device
7) model/maker
@binarybottle I feel it would be better to make a distinction between mental and bodily state which is not indicated in our revised domains (see issue #28)

16 personalities questionnaire (https://www.16personalities.com/free-personality-test)
MIND
This trait determines how we interact with our environment.
ENERGY
This trait shows where we direct our mental energy.
NATURE
This trait determines how we make decisions and cope with emotions.
TACTICS
This trait reflects our approach to work, planning and decision-making.
IDENTITY
This trait underpins all others, showing how confident we are in our abilities and decisions.

Atlas of Emotions
![screen shot 2017-10-30 at 01 15 21](https://user-images.githubusercontent.com/10529973/32156698-5b731786-bd15-11e7-9776-1a6313bea5b5.png)

![screen shot 2017-10-30 at 01 15 06](https://user-images.githubusercontent.com/10529973/32156706-60b00a9c-bd15-11e7-9352-a0089a85bb8f.png)

Also see Stan's document for domains ( see pages 31 to 38). Do you feel they have categorized symptoms well (not based on disorder but on topics like everyday activities)
BASC-3-Rating-Scales-Report-with-Intervention-Recommendations-Sample.pdf 

Anirudh OCEAN project classification (only included ones relevant to this issue)
Social interaction, Communication, Behavioral Patterns, Mental Skills, Motor Skills, Sensory related skills, Increasing a particular skill (strength), decreasing a weakness/deficit or comfort

**Comment by anirudh4792** [comment]
Discussion with Jon on 27/10 (will update Arno in next meeting) - 
Should the names of core behaviors appear in the questionnaire or just questions that represent them?
What is the purpose of having the names of core behaviors at the moment?
Anirudh's response: for internal purposes to generate questions (core behavior +dimensions) and to see how far of the symptom space we have covered

**Comment by binarybottle** [comment]
There is a lot going on in this issue.

- I believe we make an implicit distinction between mental and bodily state with our symptoms vs. signs.

- I'm not sure why our "train of thought" is in a discussion of core behaviors.

- Do we need to establish an exhaustive list of core behaviors?
