### ISSUE TITLE
Dimensional feature - recovery (how quickly can you recover from ....)

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#38]
I felt it would be interesting to add recovery (how quickly can you recover from...) to the following behaviours - activity, mood, depression, fear, anxiety (too cumbersome to spell it every time as behaviors - sorry Arno) 

Interestingly, this feature was already included under the dimension intensity in first level questions
https://docs.google.com/document/d/1bx2am3-cLJLBBbdk--WOxrp96GaszE0Te2z4jvbvMow/edit
(ctrl F for the behaviours to see)

**Comment by shnizzedy** [comment]
This dimension is interesting! I wonder if we could think of a more neutral term than "recovery" that would apply to changes back from both negative and positive behaviors and experiences.

**Comment by binarybottle** [comment]
If we're interested in how quickly [one can recover, etc.], this should be subsumed within duration, no?

**Comment by anirudh4792** [comment]
In some cases, yes - duration overlaps with recovery period. But generally,
how long a temper outburst/depressive periods lasts is different/not always
the same as how quickly one recovers from it. How long one's attention span
lasts is different from how quickly one can recover from it.

**Comment by anirudh4792** [comment]
This also paves the way for users to answer what strategies/training they
use to 'recover'.
