### ISSUE TITLE
Mind vs Intellect Domains/Concept

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#39]
Mental States/Skills related to the mind 
How I define mind - receives data from the senses and stores memory

Things related to the intellect/Applying the mind
How I define intellect - retrieves memory, analyses data from the senses, sends solutions and decisions

Sometimes, the same behaviour could be classified under both domains depending on the context
Repetitive behaviors
Hand flapping in autism or tics - I feel this is more biological/neurological and related to the mind rather than the intellect; involuntary
Switching lights on and off - I feel this is more intellect related; voluntary

So what would trichotillomania come under?
Some are conscious while others are oblivious

(see questions under mental/intellectual - https://docs.google.com/document/d/1bx2am3-cLJLBBbdk--WOxrp96GaszE0Te2z4jvbvMow/edit)
Also see issue #37

**Comment by binarybottle** [comment]
Getting into slippery territory when you are trying to attribute awareness, intent, or agency to thoughts/behaviors...

**Comment by shnizzedy** [comment]
Where do these definitions come from?

Is intellect distinct from mind, a part of mind, or do the two overlap?

Why do we want this differentiation? Are the subclasses of [`behavior`](http://www.ontobee.org/ontology/catalog/NBO?iri=http://purl.obolibrary.org/obo/NBO_0000313) in Neuro Behavior Ontology useful for such purposes?

> - agonistic behavior
> - avoidance behavior
> - cognitive behavior
> - consciousness behavior
> - consumption behavior
> - emission behavior
> - emotional behavior
> - grooming behavior
> - impulsive behavior
> - kinesthetic behavior
> - motivation behavior
> - nesting behavior
> - novelty response behavior
> - playing behavior
> - regulation of behavior
> - reproductive behavior
> - rhythmic behavior
> - social behavior
> - stress related behavior

**Comment by anirudh4792** [comment]
These definitions were defined by me to distinguish between voluntary and
semi-voluntary/involuntarily behaviors and to have some starting material
for the discussions (even if such classifications are not needed, it needs
to be determined that it is not needed).

I feel trying to attribute awareness, intent or agency is needed - yes, it
is more slippery but other questionnaires don't have this specificity
