### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#40]
From the systemizing quotient test, we have questions such as 

When I look at a painting, I usually think about the technique involved in making it.
Arno may answer yes but only because of a family run art gallery vs that is how his brain works (lamarckism vs mendelian genetics...interestingly, Lamarckism turned out to be not all false with epigenetics)

Always looks at ingredients
I look at ingredients in detail not because of my interest but to check if it is vegan

P.S
Should these be mentioned on Github as an issue or I just keep note of it in a personal google doc/wall

**Comment by shnizzedy** [comment]
I don't think these are false positives at all!

`When I look at a painting, I usually think about the technique involved in making it` doesn't say anything about *why* I think that way (nor do I think it should!).

Checking to see if food in vegan is as good a reason as any to `always look at ingredients`.

For any behavior or experience, the reasons are legion why one might answer a particular way (even a dishonest way) at a given time. The pattern across answers is where we can start to make interpretations, not at the individual question level.

**Comment by binarybottle** [comment]
A questioner tries to get at the "why" in follow up questions.  "Do you check all the ingredients because you follow a particular diet?"...

Where any of this matters (beyond fascination with personality differences) is when a thought/behavior adversely impacts one's ability to lead a productive life.  It is the duration/frequency/severity of a condition of thought/behavior that can impede a healthy lifestyle.

**Comment by anirudh4792** [comment]
My point was just this - it is a false positive in the sense that looking
at the ingredients just to check if it is vegan or looking closely at the
technique does not necessarily mean I have an aptitude for high attention
or curiosity to detail or structure which I don't. Similarly, a parent may
draw similar conclusions thinking a particular behavioral pattern means
something when it was not the case.

I was not indicating whether the questions/responses are
relevant/irrelevant and from this angle, I agree with your view. If this is
not a concern, then all is well. Maybe if a child is used to looking for
details in paintings, a similar aptitude may be induced  in him for similar
tasks

**Comment by anirudh4792** [comment]
Didnt see Arno's response while replying. I agree with the two points and I am closing the issue. I feel that identifying possible areas of aptitude besides problem areas can still possibly be ascertained irrespective of false positives.
