### ISSUE TITLE
Causality vs Reverse Causality vs No Correlation

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#41]
Does depression cause lack of sleep OR does lack of sleep cause depression OR are both unrelated?

In our first level questions, I feel we could have an added option (I saw this feature in a CMI used questionnaire) - a side option with the question 'is it affected by the other domains?' with answer options Yes or No

Domains/Categories of our questionnaire
Everyday Activities (eg sleep, eating, energy)
Mental States/Skills related to the mind
Bodily Conditions/States; Related to the body
Things related to the intellect/Applying the mind

Eg Are everyday activities affected by other domains? YES
anxiety affects sleep
illness, anorexia affects eating
depression affects energy levels

**Comment by binarybottle** [comment]
As we discussed last week, we will do just fine not to attribute causality to anything we're doing now.  We can certainly include [probability of] causality to our relationships between entities later if we want to.

**Comment by shnizzedy** [comment]
Correlation for everything all the time. Period.[<sup>‡</sup>](#dagger_note)

> Does depression cause lack of sleep OR does lack of sleep cause depression OR are both unrelated?

OR does some third factor cause lack of sleep **and** depression OR does a combination of other factors cause lack of sleep **and** depression OR does lack of sleep combined with another factor cause depression OR does a combination of lack of sleep and multiple other factors cause depression OR does depression combined with another factor cause lack of sleep OR does a combination of lack of depression and multiple other factors cause lack of sleep, etc.

Also note that these ORs are inclusive, ie, any number of them can be true without falsifying any of others. The following could be true for example: [lack of sleep causes depression AND depression causes lack of sleep](https://en.wikipedia.org/wiki/Virtuous_circle_and_vicious_circle) (to clarify, this example is extremely oversimplified and for illustrative purposes only).

<a name="dagger_note"><sup>‡</sup></a> (unless we have a clear timeline in which B always follows but never precedes A).
