### ISSUE TITLE
Review variations/examples under parent categories of "thoughts/behaviors" 

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#42]
Method: Once I had broadly determined the highest level categories, neutralized symptoms were represented as questions (eg what is your attention span), implications (eg attention to detail) and examples. This issue focusses on examples represented in angular brackets <>

An example
Social relationships/Interacting with others
<relationships <developing and maintaining relationships, appropriate to developmental level>
making friends
catching the attention of others
interested in others
Playing with others
reacting to the presence of others
interacting with others
getting help from others
response to social approach of others
interest in peers>

eg question
Intensity
How interested are you in relationships?

I am very easily disinterested in developing and maintaining relationships .
I sometimes get disinterested in developing and maintaining relationships.
I am typically interested in developing and maintaining relationships.
I am very  interested in developing and maintaining relationships.
I cannot stop trying to develop and maintain relationships

Please note: the current logic - the user selects examples that are applicable to him or adds his own example. In the case that the example will be answered differently to the highest level parent categories of "thoughts/behaviors" (in this case, social relationships), separate questions (intensity, duration, frequency, context etc.) will be generated for the example

I would be grateful if you could review these when you can in https://docs.google.com/document/d/1PDKxWGFZ0QvXJMeFDEX87F6T6u9LXAehAUvYrVnoYXM/edit

**Comment by binarybottle** [comment]
I like the current organization of high-level categories containing neutralized symptoms as questions, specified by implications of different dimensions and made clear with examples.  Your example category and implications are great, but it will take more work to get the questions to sound more natural.  Here's a quick stab at the same example question, splitting interest in relationships into (1) making new friends and (2) maintaining friendships:

[category: social interactions; implications: making friends; dimension: intensity]
(1) How interested are you in making new friends?  
 - I hate making new friends / I avoid people so that I don't have to make new friends.
 - I don't really like making new friends.
 - I like making new friends.
 - I love making new friends.
 - I am obsessed with making new friends.

[category: social interactions; implications: maintaining friendships; dimension: intensity]
(2) How interested are you in maintaining friendships?  
 - I have no interest in maintaining friendships.
 - I dislike working on my relationships with my friends.
 - I like working on my relationships with my friends.
 - I love working on my relationships with my friends.
 - I become obsessed with my friends and will not allow them to break off our friendship.

**Comment by anirudh4792** [comment]
Thank you very much. Makes things clearer for me. I was also hoping to get your views on one complicated example if possible. 

9) Do you have problems socially communicating with others?
<back and forth conversation
social approach
sharing of interests 
sharing of emotions
sharing of affect
social imitation
imitation skills, social imitation skills
social initiations
getting help from others
pragmatic use of language <clarifies if not understood, provides background information>, social use of language
response to name, response when spoken to
initiating conversation
sharing of interests
pointing out objects of interests to others
joint attention
responsive social smile
sharing emotions with others <sharing enjoyment, sharing excitement, sharing happiness>
response to praise
enjoys social interaction
offering comfort to others
response to physical contact, response to affection
initiating conversation
socio-emotional reciprocity
makes eye contact when talking>

I cannot communicate socially even with assistance.
I can communicate socially with difficulty and assistance.
I can typically communicate socially without assistance.
(4th option removed due to redundancy)
I never communicate socially despite understanding/knowing what

BONUS
Do you have problems controlling or stopping repetitions of body movements and/or behavioral patterns?
<performs hand movements <clapping, flapping>
performs whole body movements <foot to foot rocking, dipping, swaying; spinning>
walks with correct posture
body related behaviours performed when unnecessary <body tensing, facial grimacing, teeth grinding, puts hands over ears when not in response to sound, picking, squinting of eyes>
interested in movement of things <spinning wheels of toys, the opening and closing of doors, electric fans, rapidly revolving objects>
motor tics <eye blinking, shoulder shrugging, extension of extremities, simultaneous head turning, copropraxia, echopraxia>
Recurrent pulling out of one's hair, resulting in hair loss.
Repetitive skin picking>

Repetitive Behaviors
<repeats patterns of behaviors, repeats gestures>

Repetitive verbal/nonverbal behavior
<performs vocalizations <humming, squealing, sounds with intonations, guttural sounds>
vocal tics <throat clearing often caused by contraction of the diaphragm or muscles of the oropharynx, sniffing often caused by contraction of the diaphragm or muscles of the oropharynx, grunting often caused by contraction of the diaphragm or muscles of the oropharynx, palilalia, echolalia, coprolalia
Echolalia <repetition of words, repetition of phrases, repetition of songs, repetition of dialogues>

Ritualistic Behavior
<patterns in verbal behavior/, 
patterns in nonverbal behavior
asks questions about a particular topic
seeks responses in a specific way, says things in a specific way <verbal rituals>
compulsions <turning in circles before entering a room>
engages in ritualistic behavior <licking objects, sniffing objects >>

I cannot control or stop repeating body movements and/or behavioral patterns.
I can control or stop repeating body movements and/or behavioral patterns with difficulty.
I can typically control/have no problems controlling or stop performing body movements and/or behavioral patterns voluntarily.
I can repeat body movements and/or behavioral patterns when required with difficulty.
I do not repeat body movements and/or behavioral patterns even when required

**Comment by binarybottle** [comment]
Do you have problems socially communicating with others?

- I cannot communicate socially even with help.
- I can communicate socially with difficulty and with help.
- I can usually communicate socially without help.
-----   
- I never communicate socially even when I know what the other person is saying and I know what I should say.

Must we say "communicate socially"?

**Comment by shnizzedy** [comment]
> Must we say "communicate socially"?

I interpreted that phrase as a contrast to self-talk, journaling and non-communicative social behavior.

**Comment by binarybottle** [comment]
We will have to deliberate over the phrasing of just about everything, and will likely do so with the system proposed in issue #61 -- should we close this issue?
