### ISSUE TITLE
Should intensity always be the dimension in the first set of questions (eg questions on depression)

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#43]
The original intent with having intensity first up was to identify areas of interest (strengths, weaknesses etc.) to generate follow up questions. Sometimes, I feel other dimensions are more appropriate for this.

Depression
eg Emotional/Mental States resulting from depression/depressive symptoms
_Feelings of worthlessness
Feelings of excessive or inappropriate guilt
diminished ability to think or concentrate
Indecisiveness
Diminished interest or pleasure in activities
Irritable mood
appears tearful
feelings of  sadness, emptiness, hopelessness
Recurrent thoughts of death
recurrent suicidal ideation without a specific plan_

Intensity
How affected are you by depression/depressive symptoms

I do not experience depressive symptoms (this is covered by frequency, but has to be included if only intensity questions are asked in round 1)
I experience a typical amount of depressive symptoms, but I am not very affected by it
I get depressed/affected by depressive symptoms, but I can overcome it with ease
I am highly depressed/highly affected by depressive symptoms and I can overcome it with difficulty
I am so depressed/so affected by depressive symptoms that I cannot do anything else

Frequency
 How frequently do you get depressed or How frequently do you experience depressive symptoms?

I never get depressed/I never experience depressive symptoms.
I rarely get depressed/I rarely experience depressive symptoms.
I sometimes get depressed/I sometimes experience depressive symptoms.
I get depressed most of the time/I experience depressive symptoms most of the time.
I always get depressed/I always experience depressive symptoms.

**Comment by binarybottle** [comment]
If with the above you are demonstrating that it would be more reasonable to first probe depressive symptoms with frequency questions before intensity questions, I agree.  As you point out, it is not clear there even is a meaningful distinction between some dimensions when applied to a question (I never get depressed / I don't experience depressive symptoms, realizing there are other options: I am not affected by depressive symptoms / I cannot get depressed).

**Comment by binarybottle** [comment]
If this relates to our goals of creating an adaptive questionnaire, then this is an empirical question that would need to be tested.  Closing until we run our current study and have future discussions...
