### ISSUE TITLE
HealthRhythms collaboration?

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#44]
Mike Merrill, a data scientist at [HealthRhythms](https://www.healthrhythms.com), was one of the presenters at [Artificial Intelligence and Analytics in Healthcare](https://www.eventbrite.co.uk/e/artificial-intelligence-and-analytics-in-healthcare-tickets-38501837031) this morning, and from what he said, they are already doing a lot of what we're trying to do: use ecological sensor data, including voice, wearables, and phone sensors, to perform data-driven diagnostic and prognostic functions.

@binarybottle — what do you think the potential for collaboration is? Their methods and many of their goals align dramatically with ours, and they seem ahead of us in sophistication based on the panel this morning (but I wouldn't guess from their website), but their profit motive also seems much greater than ours.

@curtpw, @anirudh4792, @sgiavasis — these guys should definitely at least be on our radar for the database and for sensor data.

**Comment by binarybottle** [comment]
I might have spoken with Mike Merrill over the phone while on a teleconference meeting with Hane Aung (Tanzeem Choudhury, CEO of HealthRhythms and professor at Cornell is on sabbatical and parental leave until December).  She expressed great interest in what our plans were with voice data and suggested a visit to Cornell.  Thank you for reminding me!  Let me reconnect via email...

**Comment by binarybottle** [comment]
We discuss lab communications/collaborations in a different repo, and we have contacted Tanzeem Choudhury, so I am closing this issue.

**Comment by shnizzedy** [comment]
This issue was moved to ChildMindInstitute/matter-lab-collaboration-tracking#10
