### ISSUE TITLE
Revamped questions for sleep (improved model for questions?)

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#45]
Sleep

Select the answers that suit you the most
You can select multiple options at a time
If none of the answers are applicable, add your answer
You can add examples or descriptions to your answers

Ability
Do you have problems falling asleep?

I cannot fall asleep (insomnia).
I can fall asleep with difficulty.
I can typically fall asleep.
I can fall asleep with ease (eg while travelling)
I fall asleep with too much ease (eg falling asleep when dont want to or not expected to do so)
p.s (dedicated to Arno's article on George Church)

Which of these options best suit you? (select if applicable)
I try to, but cannot sleep well/enough (redundant with ‘I cannot fall asleep (insomnia)’
I can sleep well, but do not due to circumstances that I control (eg poor lifestyle choices)
I can sleep well, but do not due to circumstances that I cannot control (eg responsibilities)

Duration
How long do you sleep on average per day?
very short - short - typical - long - very long

Ideally, how much longer/shorter would you want sleep on average per day than you usually do?
much shorter - shorter - same - longer - much longer

Satisfaction
Are you satisfied with your sleep overall? 
Yes - Somewhere in the middle - No

Intensity or Satisfaction?
How would you describe the quality of your sleep or How satisfied are you with your sleep?

I have very poor quality of sleep <very easily disturbed, gets up often, feels very tired after sleep>
I have poor quality of sleep.
I have a typical quality of sleep.
I have high quality of sleep (eg rarely disturbed, gets up rarely, feels refreshed after sleep)
I have an extremely high quality of sleep ( eg sleeps so deep that does not feel refreshed)

Frequency
How often do you have problems with sleep?

I never have problems with sleep.
I rarely have problems with sleep.
I sometimes have problems with sleep.
I have problems with sleep most of the time.
I always have problems with sleep.

Context
Do outside factors affect your quality of sleep?

I sleep well anytime, anywhere.
Sleeping well depends somewhat on context.
Sleeping well depends on context.
Sleeping well depends a lot on context.
I can sleep well only under particular conditions.

Points to Note
I really liked satisfaction and ideal situations (its something questionnaires dont usually have and provides rich context) - I have tried to include them
I would like to make a difference between cannot do & can, but wont do
Must all the scales be uniform (I thought of combining cannot do & can, but wont do under ability by providing more options)
I know we initially discussed not having opposite behaviors, but is 'I cannot sleep well only under particular conditions' well represented by 'Sleeping well depends somewhat on context.' I feel we could just include it when applicable

@binarybottle @shnizzedy - do you think these questions are reasonable? I am trying to take Arno's approach to grant writing carefully constructing the aims (in this case, representation of dimensions and structure) vs the usual brute force approach

**Comment by shnizzedy** [comment]
I really like how these questions are framed. My answers and line-item responses (where I have any) below:

---

> Ability
> Do you have problems falling asleep?

I can fall asleep with ease (eg while traveling)

> Which of these options best suit you? (select if applicable)

Sometimes I try to, but cannot sleep well/enough (redundant with ‘I cannot fall asleep (insomnia)’
Sometimes I can sleep well, but do not due to circumstances that I control (eg poor lifestyle choices)
Sometimes I can sleep well, but do not due to circumstances that I cannot control (eg responsibilities)

> Duration
> How long do you sleep on average per day?

long
would sleep very long if I could

> Ideally, how much longer/shorter would you want sleep on average per day than you usually do?

longer
(😄 you anticipated my last comment!)

> Satisfaction
> Are you satisfied with your sleep overall?

Somewhere in the middle

> Intensity or Satisfaction?
> How would you describe the quality of your sleep or How satisfied are you with your sleep?

I have a typical quality of sleep.

> Frequency
> How often do you have problems with sleep?

I sometimes have problems with sleep.

> Context
> Do outside factors affect your quality of sleep?

Sleeping well depends somewhat on context.

---

> Points to Note
> I really liked satisfaction and ideal situations (its something questionnaires dont usually have and provides rich context) - I have tried to include them

Me too!

> I would like to make a difference between cannot do & can, but wont do
> Must all the scales be uniform (I thought of combining cannot do & can, but wont do under ability by providing more options)

Maybe let's try a couple examples of both options and we can all see what we think?

**Comment by binarybottle** [comment]
Any resolution here?  Close?
