### ISSUE TITLE
Try some text-based adventure games!

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#46]
[Text-Based Adventure Games](https://github.com/ChildMindInstitute/mhdb/wiki/Text-based-adventure-games)

**Comment by binarybottle** [comment]
We list some text-based adventure games in our wiki (https://github.com/ChildMindInstitute/mhdb/wiki/Links#text-based-adventure-games), but I'm not sure how relevant this issue is until we have completed our survey studies and are closer to creating an adaptive questionnaire, so closing this issue.
