### ISSUE TITLE
Revamped questions for one domain (whose name shall not be mentioned) for review

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#47]
Acting on Arno's suggestion, I have included only the questions to facilitate easy reviewing and not the options (for an example of options, look at issue #45 ). Please let me know what you think and I can proceed with other domains. 

Sleep
Do you have problems falling asleep?
Which of these options best suit you? (select if applicable) (tries but cant sleep, can sleep but doesnt)
How long do you sleep on average per day?
Ideally, how much longer/shorter would you want sleep on average per day than you usually do?
Are you satisfied with your sleep overall? (yes, no, somewhere in between)
How would you describe the quality of your sleep or How satisfied are you with your sleep?
How often do you have problems with sleep?
Do outside factors affect your quality of sleep?

These are examples of behaviors/situations seen in normal back and forth conversations
pragmatic use of language <clarifies if not understood, provides background information>
responding to name, responding when spoken to
initiating conversations
These are examples of unusual behaviors/situations seen in back and forth conversations
<One‐sided conversations/monologues/tangential speech>
Do you have problems with such behaviors/situations in normal back and forth conversations?
How much of a problem do you have with such behaviors/situations in normal back and forth conversations?
How often do you  have a problem with such behaviors/situations in normal back and forth conversations?
Do outside factors affect your usage of such behaviors/situations in normal back and forth conversations?
 
Sharing emotions
<disappointment, happiness, sadness, distress>
Do you have problems sharing your emotions?
Do you respond with emotions when appropriate?
<responsive social smile; responding to praise; offering comfort to others; responding to affection>
How long does your expression of emotions last?
Are you satisfied with how you share your emotions?
Ideally, how much would you want to share your emotions?
Which of these options best suit you? (select if applicable) (does understand emotions, but prefers not to share them; does not understand emotions and hence does not share them)
How often do you express your emotions?
Do outside factors affect your sharing of emotions?

Social skills 
These are considered as examples of skills used during social interactions
<imitation - engaging in simple social games;  joint attention; imaginative/symbolic play>
Do you have problems using such skills?
Does using such skills depend on context?
Which of these options best suit you? (select if applicable) (knows how to use such skills but does not use them; has impairments in using such skills); 

Do you have problems adjusting your behavior to suit social contexts?
<using proper etiquette when required; behaving in accordance to social conventions < asking socially appropriate questions; making socially appropriate statements>
Which of these options best suit you? (select if applicable) (understands and is aware of social conventions, but does not follow them; does not understand social conventions and cannot follow them; does not understand social conventions and is trained to follow them)
How often do you behave according to social norms?
Do outside factors/context affect your adjustment of behavior in social situations?
<depends on my mood>
 
Social initiations
Do you have problems initiating social interactions?
Which of these options best suit you? (select if applicable) (understands and is aware of social conventions, but does not follow them; does not understand social conventions and cannot follow them; does not understand social conventions and is trained to follow them; Note: redundant - understands and is aware of social conventions have already been asked)
How often do you initiate social interactions?
Does initiation of social interactions depend on context?
 
These are examples of abnormal social behavior 
<unusual initiations (eg intrusive touching, licking of others>
Do you have any problems abstaining from abnormal social behavior?
How often do you engage in abnormal social behavior?
Does engagement in abnormal social behavior depend on context?

Developing friendships/relationships
How interested are you in making new friends?
Which of these options best suit you? (select if applicable) (interested in making friends, but does not understand social conventions <too direct or passive, rigid>; understands social conventions but does not maintain friendships)
How often do you make new friends?
Does making new friends depend on context?
Are you satisfied with the number of friendships you have OR Ideally, how many friends would you want to have?
 
Maintaining relationships
How interested are you in maintaining relationships/friendships?
How long do your relationships last?
How often do you maintain your relationships?
Does your ability to maintain relationships depend on context?
Are you satisfied with how you maintain your relationships OR Ideally, how long would you like to maintain relationships?
 
Interest in interacting with others
How interested are you in interacting with others?
Does interacting with others depend on context?
How often are you genuinely interested in interacting with others?
Are you satisfied with your interest in others OR Ideally, would you want to be more/less interested in others?
 
Social interactions
Do you have problems while interacting socially with others?
How often do you face difficulties while interacting socially with others?
Does your ability to interact with others depend on context?
Are you satisfied with how you interact socially?
Are you satisfied with how others interact with you socially?
Ideally, how much would you want to interact with others socially?
Which of these options best suit you? (select if applicable) (I dont think I have deficits in social interactions, but I prefer not to engage in them/disinterested in them; I have impairments/deficits in social interactions;

**Comment by shnizzedy** [comment]
> Do you have problems falling asleep?

- [x] Not usually.

Maybe "How easily do you fall asleep?"

> Which of these options best suit you? (select if applicable) (tries but cant sleep, can sleep but doesnt)

- [x] Sometimes tries but can't sleep
- [x] Sometimes can sleep but don't
- [x] Usually can and do sleep

> How long do you sleep on average per day?

- [x] 7 hours 5 minutes

> Ideally, how much longer/shorter would you want sleep on average per day than you usually do?

- [x] 2 hours 55 minutes longer

> Are you satisfied with your sleep overall? (yes, no, somewhere in between)

- [x] Somewhere in-between, closer to "yes" than to "no"

> How would you describe the quality of your sleep or How satisfied are you with your sleep?

- [x] Fine. / I have a typical quality of sleep.

This one (these?) is (are) hard to feel satisfied with an answer. In the example responses, factors of disturbance, getting up, and feeling refreshed are grouped together; I think I could answer each of those factors on its own in less than a third the time it took me to try to quantify my sleep quality and satisfaction.

- [x] I am almost never disturbed while sleeping.
- [x] I usually get up 1–2 times a night.
- [x] I usually feel tired when I wake up.

> How often do you have problems with sleep?

- [x] I sometimes have problems with sleep.

> Do outside factors affect your quality of sleep?

- [x] Sometimes.

This question could stand to be more specific, I think, though examples might clear up my confusion. <a name="outside_disambiguate"></a>What are "outside factors"? Noises? Responsibilities? Illness? All of these?

> These are examples of behaviors/situations seen in normal back and forth conversations
> pragmatic use of language <clarifies if not understood, provides background information>
> responding to name, responding when spoken to
> initiating conversations
> These are examples of unusual behaviors/situations seen in back and forth conversations
> <One‐sided conversations/monologues/tangential speech>
> Do you have problems with such behaviors/situations in normal back and forth conversations?

- [x] Sometimes.

Again, asking how easily one performs such behaviors could be less stigmatizing than asking about problems.

> How much of a problem do you have with such behaviors/situations in normal back and forth conversations?
> How often do you have a problem with such behaviors/situations in normal back and forth conversations?
> Do outside factors affect your usage of such behaviors/situations in normal back and forth conversations?

My last two responses apply to these three questions.

> Sharing emotions
> <disappointment, happiness, sadness, distress>
> Do you have problems sharing your emotions?

- [x] Sometimes.

> Do you respond with emotions when appropriate?
> <responsive social smile; responding to praise; offering comfort to others; responding to affection>

- [x] Usually.

> How long does your expression of emotions last?

- [x] It depends on how deeply I felt the emotion(s) I was expressing and on what, if anything, I was attempting to communicate with the expression.

This question has some interesting considerations:

| | feeling | not feeling
|-|-------|------------
|expressing |😊|🙂
|not expressing |😔|😑

Even within each cell of the above table, I probably have variation in my answer to this question, and across cells my answer can be quite different.

> Are you satisfied with how you share your emotions?

- [x] <table><tr><td></td><td>**feeling**</td><td>**not feeling**</td></tr><tr><td>**expressing**</td><td>usually</td><td>almost always</td></tr><tr><td>**not expressing**</td><td>almost always</td><td>usually</td></tr></table>

> Ideally, how much would you want to share your emotions?

- [x] It depends with whom and what emotions (and real emotions or emotions intended to communicate something)

> Which of these options best suit you? (select if applicable) (does understand emotions, but prefers not to share them; does not understand emotions and hence does not share them)

- [x] does understand emotions, but prefers not to share them
- [x] does not understand emotions and hence does not share them
- [x] does understand emotions, and shares them as experienced
- [x] does understand emotions, and shares unexperienced emotions to communicate or manipulate

> How often do you express your emotions?

- [x] <table><tr><td></td><td>**feeling**</td><td>**not feeling**</td></tr><tr><td>**expressing**</td><td>rarely</td><td>often</td></tr><tr><td>**not expressing**</td><td>often</td><td>almost always</td></tr></table>

> Do outside factors affect your sharing of emotions?

- [x] Always, if "outside factors" includes the audience with which I am or am not sharing my emotions.

As <a href="#outside_disambiguate">above</a> "outside factors" needs disambiguation.

The structure for the rest of these examples is comparable to the above examples, so I'd only be repeating myself if I responded to the rest.

**Comment by anirudh4792** [comment]
Thank you both for the discussion and suggestions @shnizzedy and @binarybottle . For this attempt, I have

- made the questions simple, concise and in a manner in which you can come into the office, ask any question and be understood.
- Implemented Jon's suggestion (Again, asking how easily one performs such behaviors could be less stigmatizing than asking about problems: I have removed the word 'problem'as much as possible)
- Not added all the dimensions like frequency, duration etc. (just base questions)

Select the answers that suit you the most
You can select multiple options at a time
If none of the answers are applicable, add your answer
You can add examples or descriptions to your answers

Do you have difficulties falling asleep OR Do you fall asleep with ease?
How interested are you in making new friends?
How interested are you in maintaining relationships/friendships?
How interested are you in interacting with others?
Do you have difficulties conversing with others OR Can you converse with others with ease?
Do you use language pragmatically when required with others?
<clarifies if not understood, provides background information>
Do you respond to others when spoken to?
Do you respond when your name is called?
While conversing with others, do you speak in monologues?
While conversing with others, are the conversations one-sided?
Is your speech tangential while conversing with others?
Do you share your emotions with others?
When others smile at you, do you smile back?
Do you offer comfort to others when they are in pain?
While responding to others, do you express your emotions?
<responding to praise; responding to affection>
Can you use imitation skills to engage in simple social games?
Can you engage in joint or shared attention with others on an object?
Can you engage in social role playing?
Do you use proper etiquette when required in social situations?
Do you ask irreverent or inappropriate questions in social situations?
Do you initiate social interactions? OR Do you have problems initiating social interactions?
While interacting with others, do you initiate your interactions unusually?
<intrusive touching, licking of others>
How well do you interact with others socially?

Interestingly, all information in this domain has been covered for, at the cost of more questions but more clarity which we all agree on, and got rid of any groupings.
My biggest concern at this point is how we incorporate the drop-down menu or encourage the user to add his/her questions and examples (I somehow feel this is easier with a parent group with examples, where parents can select what they want and add their own, though I am starting to feel this is only an illusion and parents can do the same with the above format). Also, I feel we must be cautious not to revert to existing questionnaires style that the above questions seemingly resemble)

**Comment by binarybottle** [comment]
This is getting closer.  You are right, that each question may require significant crafting of words.  We should still think about how we could generate questions semi/automatically to work from, either by deconstructing clear examples and repurposing (and randomly altering) the wording or training a learning algorithm.

**Comment by anirudh4792** [comment]
Here are the above questions + different dimensions
Note: the questions that stand independently (exists on its own with only one dimension needed to satisfactorily ask that question) were the ones I tried to group together. The way they stand, they seem a bit like traditional questionnaires

How interested are you in making new friends?
Which of these options best suit you? (select if applicable) (interested in making friends, but does not understand social conventions <too direct or passive, rigid>; understands social conventions but does not maintain friendships)
How often do you make new friends?
Does making new friends depend on context?
Are you satisfied with the number of friendships you have OR Ideally, how many friends would you want to have

How interested are you in maintaining relationships/friendships?
How long do your relationships last?
How often do you maintain your relationships?
Does your ability to maintain relationships depend on context?
Are you satisfied with how you maintain your relationships OR Ideally, how long would you like to maintain relationships?
 
Interest in interacting with others
How interested are you in interacting with others?
Does interacting with others depend on context?
How often are you genuinely interested in interacting with others?
Are you satisfied with your interest in others OR Ideally, would you want to be more/less interested in others?

Do you have difficulties conversing with others OR Can you converse with others with ease?
How long do your conversation with others typically last? 
Ideally, how much would you like to converse with others?
Are you satisfied with the way you converse with others?
Does conversing with others depend on context?

Do you use language pragmatically when required with others?
<clarifies if not understood, provides background information>

Do you respond to others when spoken to?
Does responding to others depend on context?

Do you respond when your name is called?

While conversing with others, do you speak in monologues?
Does speaking in monologues with others depend on context?

Are your conversations with others one-sided?
Are most of your conversations one-sided or do they depend on context?

Is your speech tangential while conversing with others?
Does your tangential speech depend on others?
How often is your speech tangential while conversing with others?

With how much ease/How effectively can you share your emotions with others?
<disappointment, happiness, sadness, distress>
How often do you share/express your emotions with others?
Does sharing emotions with others depend on context?
Do outside factors affect your sharing of emotions?
Which of these options best suit you? (select if applicable) (does understand emotions, but prefers not to share them; does not understand emotions and hence does not share them)
Ideally, how much would you want to share your emotions?
Are you satisfied with the way you express your emotions?

Do you offer comfort to others when they are in pain?
 
While responding to others, can you adapt your emotions appropriately to the situation?
<responding to praise; responding to affection>
 
When others smile at you, do you smile back?
 
Can you use imitation skills to engage in simple social games?

Can you engage in joint or shared attention with others on an object?

Can you engage in social role playing?

Do you use proper etiquette when required in social situations?

Do you ask irreverent or inappropriate questions in social situations?
 
How easily can you initiate social interactions? OR Do you have problems initiating social interactions?
How often do you initiate social interactions?
Does your initiation of social interaction depend on context?
In an ideal situation, how much would you like to initiate social interactions more than what is absolutely necessary? OR Ideally, how much would you initiate social interactions?

While interacting with others, do you initiate your interactions unusually?
<intrusive touching, licking of others>

With how much ease can you interact with others socially?
How often do you interact with others socially?
How well do you think you interact with others socially?
Ideally, how much would you like to interact with others?
Does your engagement in social interactions depend on context?

Do you have difficulties falling asleep OR Do you fall asleep with ease?
Which of these options best suit you? (select if applicable) (tries but cant sleep, can sleep but doesnt)
How long do you sleep on average per day?
Ideally, how much longer/shorter would you want sleep on average per day than you usually do?
Are you satisfied with your sleep overall? (yes, no, somewhere in between)
How satisfied are you with your sleep?
How often do you have problems with sleep?
Do outside factors affect your quality of sleep?

**Comment by binarybottle** [comment]
Can we close this issue, as everything we do will require some deliberation over delivery, and we will likely be voting on different phrasings using the system in issue #61 ?  We can of course reopen this issue if we continue to struggle with this later.
