### ISSUE TITLE
Questionnaire descriptions and instructions

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mhdb#48]
"Let's try to take a snapshot of who you are -- an accurate picture of your inner life, right now, that goes beyond standard personality profiles.  The more questions you answer, the more complete a picture you will have of yourself.  Please try and select the best answer(s) to each question. You can choose more than one answer, skip any question, or add your own answer with your own descriptions and examples!"

What to call the assessment:
  - snapshot
  - picture
  - profile
  - outline
  - representation
  - character(ization)
  - avatar
  - virtual you
  - mental survey
  
Possible motivations to complete:
  - gain a better understanding of oneself or a loved one
  - contribute to science
  - learn from and help others like yourself
  - compare profiles with friends
  - create an avatar
  - find others / celebrities like yourself
  - learn your strengths and weaknesses
  - track your inner life over time
  - get help
  - find relevant publications
  - find appropriate apps/wearable/games
  - be the main character in a build-your-own adventure style narrative

**Comment by shnizzedy** [comment]
> What to call the assessment:

[. . .]
> - **representation**
> - **character(ization)**

I like these options a lot, emphasizing the reductive and imprecise nature of this type of exercise

> - avatar

We've got a lot of precedent competition for this name:
[![Avatar: The Last Airbender](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Avatar_The_Last_Airbender_logo.svg/200px-Avatar_The_Last_Airbender_logo.svg.png)](https://en.wikipedia.org/wiki/Avatar:_The_Last_Airbender), [![Avatar (Cameron)](https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/Avatar-Teaser-Poster.jpg/220px-Avatar-Teaser-Poster.jpg)](https://en.wikipedia.org/wiki/Avatar_(2009_film)), [![Avatar (Kuo)](https://upload.wikimedia.org/wikipedia/en/thumb/5/51/Avatar_FilmPoster.jpeg/220px-Avatar_FilmPoster.jpeg)](https://en.wikipedia.org/wiki/Avatar_(2004_film)), [![AVATAR MUD](https://upload.wikimedia.org/wikipedia/en/9/92/Avatar_MUD_logo.png)](https://en.wikipedia.org/wiki/AVATAR_(MUD)), [![Avatar (X-Box)](https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Xbox_Avatars_Changing_Hair.png/220px-Xbox_Avatars_Changing_Hair.png)](https://en.wikipedia.org/wiki/Avatar_(Xbox_Live))

To be clear, I think we should definitely consider building avatars in one or more of this projects deliverables, but that the name "avatar" is way too diluted to use. An A.C.R.O.N.Y.M. that includes "avatar", on the other hand… "Avatar Creation Research Opportunity, Not Your Mother"?

> Possible motivations to complete:

[. . .]
> - be the main character in a build-your-own adventure style narrative

A fun longer-term motivation could include a character that can be used in other games, like [Mii](https://en.wikipedia.org/wiki/Mii)/[Amiibo](https://en.wikipedia.org/wiki/Amiibo), [Disney Infinity](https://en.wikipedia.org/wiki/Disney_Infinity), or [Sonic & Knuckles](https://en.wikipedia.org/wiki/Sonic_%26_Knuckles).

~ ![Jon's mii](https://cdn-mii.accounts.nintendo.com/2.0.0/miis/23d5b850d4239dbc/image/bdcc2bb190458547-ad2cba2dc753e6db.png)

**Comment by binarybottle** [comment]
- "Not Your Mother" is always good to include in an acronym to differentiate from others' mother avatars.  
- avatar in other games?  interesting...

**Comment by binarybottle** [comment]
We can refer to these notes in the future when we are closer to applying our database to an adaptive questionnaire (M3Q).  Closing for now to clear our heads and focus...
