### ISSUE TITLE
demographics?

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#50]
I was listening to ["What about the Myers-Brigg of Sexuality?"](https://soundcloud.com/user-863387665/episode-18-what-about-the-myers-briggs-of-sexuality-featuring-ashe) on my commute in this morning and was pleased to hear a demand for the type of platform that we are building. The discussants specifically criticized [the Kinsey Scale](https://en.wikipedia.org/wiki/Kinsey_scale) and [The Klein Sexual Orientation Grid](https://en.wikipedia.org/wiki/Klein_Sexual_Orientation_Grid) as having too few dimensions, that human behaviors and experiences make more sense on spheres than on line segments!

I like how the KSOG asks for past, present, and ideal responses to each question (see issue #36), and how those terms are specifically and consistently defined as "from early adolescence up to one year ago", "within the last 12 months", and "what would be chosen if it were voluntary", respectively.

The episode got me wondering:

1. Are we planning on including demographics in our questionnaire(s)?

and if so, 

2. Can we apply our dimensions to demos?
3. Should we?

| pros | cons |
|---|---|
|another opportunity to reframe problematic abstractions|potential increased danger of reidentification|
|increased generalizability|greater quantity of questions|

**Comment by binarybottle** [comment]
It could be an optional supplement to complete one's profile.  We need to discuss further about privacy/reidentification issues.

**Comment by binarybottle** [comment]
Demographics are probably going to be constrained to those used in standard instruments in common use and approved by IRBs.  Since MIndLogger opens up anything to the Editor, dimensions to demographics will certainly be on the table.  Thank you for raising this issue.
