### ISSUE TITLE
signOrSymptom

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#51]
Replace :hasSignOrSymptom with [health-lifesci:signOrSymptom](http://health-lifesci.schema.org/signOrSymptom)

**Comment by binarybottle** [comment]
"A sign or symptom of this condition. Signs are objective or physically observable manifestations of the medical condition while symptoms are the subjective experience of the medical condition."

This is fine, but for our neutral case, where we are thinking more broadly than medical conditions, even to extraordinary abilities, wouldn't "state" be better, given that one could be in different and dynamic physical, physiological, phenotypic, genomic, mental, emotional, cognitive, or other states of body or mind?

**Comment by binarybottle** [comment]
It is pretty silly that health-lifesci:MedicalSignOrSymptom subsumes health-lifesci:SignOrSymptom, but if so, then it makes sense to replace with the former.

**Comment by shnizzedy** [comment]
There is no `health-lifesci:SignOrSymptom`. Right now we're using `mdhb:SignOrSymptom`, an equivalent class to `health-lifesci:MedicalSignOrSymptom` that we created but have only defined by its relationships. My only reservation in scrapping `mdhb:SignOrSymptom` in favor of `health-lifesci:MedicalSignOrSymptom` is if the latter class' definition is too vague, too specific or otherwise insufficient for how we care to define these "states".
