### ISSUE TITLE
Class and property definitions

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#52]
Update the [Class](https://docs.google.com/spreadsheets/d/13a0w3ouXq5sFCa0fBsg9xhWx67RGJJJqLjD_Oy1c3b0/edit#gid=732674699) and [Property](https://docs.google.com/spreadsheets/d/13a0w3ouXq5sFCa0fBsg9xhWx67RGJJJqLjD_Oy1c3b0/edit#gid=70533308) sheets so that:

- every column in every sheet in each of the [mentalhealth](https://docs.google.com/spreadsheets/d/13a0w3ouXq5sFCa0fBsg9xhWx67RGJJJqLjD_Oy1c3b0), [revised structure for neutral states & lead questions](https://docs.google.com/spreadsheets/d/1REHmDXldCZ_L403Zq0N0LdhwNNEAXEIJHcNHzOIjnSQ) and [Wearables_app_tech](https://docs.google.com/spreadsheets/d/1WY_htkqFlPn5eLp2GCelBsfCoqMHqIJUYu23ShIxtT4) workbooks has at least one of:
  - a definition and source
  - a sameAs class or property
  - an equivalentClass class or property (ideally, we'd have a definition also for each of these that is different from the one we're linking to; if the external definition is exactly what we want, we should use sameAs
- Classes and Properties that have a subClassOf each has a definition that spells out how the Class or Property is more specific than its parent
- Columns that are alike in kind map to the same definition, class or property where appropriate. Eg, see the discussion in issue #51 regarding `symptom`, `neutral behavior 1`, `neutral behavior 2`, `neutral behavior 3` and `SignOrSymptom` all being either [`health-lifesci:MedicalSignOrSymptom`](http://health-lifesci.schema.org/MedicalSignOrSymptom)s or `mhdb:SignOrSymptom`s, and if the latter, how our class definition (currently nonexistent) would differ from schema.org's, "Any feature associated or not with a medical condition. In medicine a symptom is generally subjective while a sign is objective."

The ontologies in the [Ontologies spreadsheet](https://docs.google.com/spreadsheets/d/13a0w3ouXq5sFCa0fBsg9xhWx67RGJJJqLjD_Oy1c3b0/edit#gid=936740418) (the links in the cells are prefix URIs and import URIs, so many of them may not resolve on their own) are a good place to start looking for definitions.

As a reminder, Classes are entities, and Properties are relationships, so triples are always `Class` `property` `Class`.

**Comment by binarybottle** [comment]
All resolved?

**Comment by shnizzedy** [comment]
Being resolved in #53
