### ISSUE TITLE
Rating classification system added to the spreadsheet?

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#59]
Do you think it would be a good idea to get all the categories from the google doc and add it as categories (columns) in our spreadsheet for the projects (apps, wearables etc.)?
https://docs.google.com/document/d/17qamznEEkbyAfDfdy1ha_L_CDlArUU5ex5aO1TCOjzM/edit

Once we decide on rating scales, I could add the evaluation as a column index with the category in the main sheet with the options themselves being categories.
(eg. SubjectiveUserExperience_index with 1-poor, 5-great etc.)

**Comment by shnizzedy** [comment]
If we want to do anything moving the documents to spreadsheet(s) <span style="font-size:75%">(I'm not convinced that we need to yet)</span>, I'd suggest making a new workbook for it.

That being said, what besides the rating scale would we be adding at this point? If nothing, I vote for keeping it in a text doc for now.

**Comment by anirudh4792** [comment]
*That being said, what besides the rating scale would we be adding at this
point?*
besides the rating scale, it would be the criteria you used for your
wearables paper (eg location, size etc.)

Why I feel it needs to be exported is because I shall be seeding the
database further, and I would have to fill in the rating scales and
wearable criteria anyway for future entries.

**Comment by shnizzedy** [comment]
Oh, I totally forgot to send you the criteria we used for that evaluation. A lot of these may not be applicable. Here they are:  

- Activity sensors
- Accelerometer range
- Accelerometer resolution
- Gyroscope
- Magnetometer
- Altimeter
- GPS
- Inertial movement unit
- Physiology sensors
- Photoplethysmograph
- Electrodermal
- Thermopile
- Moisture sensor
- Light sensor
- Pulsewave sensor
- Inferential measures
- Active minutes
- Sleep duration
- Sleep quality
- Sleep stages
- Skin temperature?
- Heart rate
- Heart rate variability
- Practical issues
- Raw data
- (Reported) Battery life
- Water resistance
- Child-size form factor?
- Weight
- Fashion statement
- Price
- Additional notes
- Data collection
- Other sensors
- Concerns
- Additional selling points
- Experience
- Comfort
- Battery life
- Indicator clarity
- Software interface
- Download time
- Recommended use

**Comment by anirudh4792** [comment]
Thanks.

Moisture and pulsewave sensors have been added under sensors.

battery life, download time, weight, water resistance, sizes can be added
under specs that the developer would fill.

Comfort seems a nice option to include under SubjectiveUserExperience.

The rest have been accounted for.

**Comment by binarybottle** [comment]
If they have all been accounted for, shouldn't this issue be closed?  I would also make the title more descriptive, like "Include rating criteria from the actigraphy wearable device study" and provide a link to the biorxiv article in this issue.

**Comment by binarybottle** [comment]
I think that we'll be revisiting rating scales in a later (rdf) incarnation of this database, so closing.
