### ISSUE TITLE
Distinguishing signs vs symptoms

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#62]
Not surprisingly, there are not too many signs (marked with index 1 in a copy of the existing spreadsheet), with the same signs presenting themselves across different contexts/disorders (eg shaking during a panic attack vs shaking due to alcohol withdrawal)

The disorders/cases were signs are present are
panic disorder, repetitive motor movements, tic disorders (both vocal and motor), weight loss or weight gain, language disorders (reading: inaccurate reading, writing - spelling mistakes), speaking disorders (eg stuttering - # of stutter words), physical symptoms associated with substance abuse and withdrawal.

I had some difficulties classifying some (eg repetitive use of objects - can we count the number of times the object is used, sleep disorders, eating disorders (eg attempt to binge eat within two hours can be counted)

Next steps
mapping to indirectly measure symptoms through signs (eg blushed face can in turn be measured by redness)

**Comment by binarybottle** [comment]
So can you close this issue and open a new issue "Map signs to symptoms"?
