### ISSUE TITLE
Type of things/claims that a project (apps, wearables..) addresses has been categorized

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#65]
Based on my discussion with Jon (and the nice prior work grouping emotion related entries under emotional state), and subsequent discussion with Arno that knowing the general area that a project addresses (eg app addresses sleep), 

'Thing' column currently exists in the form 'relationship/'property'/adjective + noun/verb (eg improved + sleep = improved sleep)
Now, improved sleep is categorized under sleep

I have categorized the 'Thing' column in thing-mentalhealthtechnology3 by indexing from and creating a new sheet 'ThingCategory'

I am happy with the results as 'thing' seems more organized and structured, and it facilitates mapping with multiple symptoms. 
Note: I had similar intentions to map symptoms to questions from questionnaires until it was temporarily shelved, and I am glad I will get another chance to do it.

Eg reduces stress; controls stress; monitors stress levels etc. are categorized under stress

**Comment by binarybottle** [comment]
The title suggests that this issue should be closed, no?
