### ISSUE TITLE
XLS to RDF 2: Separating signs and symptoms - revised structure for neutral states & lead questions AKA Neutral behaviors linked to other components

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#74]
~~⛄ [workbook](https://drive.google.com/open?id=1sQp63K5nGrYSgK2ZvsTfTDmlM4W5_eFHfy6Ckoi7yP4)~~ [workbook](https://docs.google.com/spreadsheets/d/1LeLlrsvBWMYTTIXTVtkynmBzzb0Uzi1OwpRLfyRAwzM)
📋 [to-do list of columns](https://drive.google.com/open?id=1JMgHilJqOklsRE6Cy7fBgyxr_CyIB3L6uAkGJLa8gS8)

**Comment by binarybottle** [comment]
We have made progress distinguishing signs and symptoms, revising behaviors as neutral states, and revising prefixes (and removed suffixes) to turn behaviors into questions.
