### ISSUE TITLE
XLS to RDF 3: mentalhealth AKA Disorders, symptoms and existing questionnaires

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#75]
~~⛄ [workbook](https://drive.google.com/open?id=1MfW9yDw7e8MLlWWSBBXQAC2Q4SDiFiMMb7mRtr7y97Q)~~ [workbook](https://docs.google.com/spreadsheets/d/13a0w3ouXq5sFCa0fBsg9xhWx67RGJJJqLjD_Oy1c3b0)
📋 [to-do list of columns](https://drive.google.com/open?id=1JMgHilJqOklsRE6Cy7fBgyxr_CyIB3L6uAkGJLa8gS8)

**Comment by binarybottle** [comment]
dsm5, projects, and people incorporated!
