### ISSUE TITLE
XLS to RDF: 02/23 mentalhealthtechnology3 + OCEAN AKA mental health projects and tech

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#76]
~~⛄ [workbook](https://drive.google.com/open?id=1cuJXT1Un7HPLYcDyHAXprH-wGS1azuUNmVQnb3dV1cY)~~ 🏂 [workbook](https://drive.google.com/open?id=1OHtVRqRXvCUuhyavcLSBU9YkiEJfThFKrXHmcg4627M)
📋 [to-do list of columns](https://drive.google.com/open?id=1JMgHilJqOklsRE6Cy7fBgyxr_CyIB3L6uAkGJLa8gS8)

**Comment by shnizzedy** [comment]
Related: #79, #80

**Comment by shnizzedy** [comment]
project dcterms:subject thing

**Comment by binarybottle** [comment]
@anirudh4792 has incorporated relevant OCEAN projects.
