### ISSUE TITLE
XLS to RDF 4: Mapping_ Similar Tasks across Cognitive Batteries AKA cognitive tasks mapped to other components

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#77]
~~⛄ [workbook](https://drive.google.com/open?id=1RfPtYPUmdMuN4sSTrvFmbeSwuTFpBCJabbIfuMynMtk)~~ [workbook](https://docs.google.com/spreadsheets/d/1VUf3XnieYThY8OA6JWtpNP4zI2xa9xak9LXuyH_PaoE)
📋 [to-do list of columns](https://drive.google.com/open?id=1JMgHilJqOklsRE6Cy7fBgyxr_CyIB3L6uAkGJLa8gS8)

**Comment by binarybottle** [comment]
We have (cognitive) tasks directly mapped to cognitive domains and to software -- will that suffice?

**Comment by binarybottle** [comment]
@anirudh4792 mapped similar cognitive tasks to each other, tasks to cognitive domains!
