### ISSUE TITLE
👶 👧 👩 👴 age_group

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#78]
For "[age_group](https://docs.google.com/spreadsheets/d/1LeLlrsvBWMYTTIXTVtkynmBzzb0Uzi1OwpRLfyRAwzM/edit?usp=sharing)", we have
- all
- adults
- children
- children and adolescents

@anirudh4792 ― Do we have loose (suggested) and/or hard (required) upper and/or lower limits on any of these? I'd guess "all" has no limits and "adults" might have a soft bottom at 18, yes?

What about "children"? "Children and adolescents"?

Ref #74

**Comment by binarybottle** [comment]
@anirudh4792 -- feel free to close this issue once you add the age_min and age_max values for the different tasks, questionnaires, etc.

**Comment by binarybottle** [comment]
We now have min/max ages + age_group.
