### ISSUE TITLE
🖇 Project ~ Disorder

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#79]
How does _[02/23 mentalhealthtechnology3 + OCEAN :: Project](https://docs.google.com/spreadsheets/d/1OHtVRqRXvCUuhyavcLSBU9YkiEJfThFKrXHmcg4627M/edit#gid=274240996) :: **project**_ relate to _[02/23 mentalhealthtechnology3 + OCEAN :: Project](https://docs.google.com/spreadsheets/d/1OHtVRqRXvCUuhyavcLSBU9YkiEJfThFKrXHmcg4627M/edit#gid=274240996) :: **disorder_index**_? My intuition is that project is the subject and disorder is the object.

- Project provides information about disorder?
- Project treats disorder?
- Project cures disorder?
- Project causes disorder?
- Project was developed in response to disorder?
- Project emulates disorder?
- Project exacerbates disorder?
- Something else?

**Comment by anirudh4792** [comment]
project addresses/inferred to address disorder.

eg., the wearable to track food habits addresses eating disorders


   - Project provides information about disorder? - doesnt fit
   - Project treats disorder? - mitigates would be a better word here
   - Project cures disorder? - that is the hope
   - Project causes disorder? - Oh no, that is not the hope
   - Project was developed in response to disorder? - could be
   - Project emulates disorder? -
   - Project exacerbates disorder? - lets hope not

**Comment by shnizzedy** [comment]
I'm sorry, I didn't mean for you to answer each bullet; those were intended as choose-one options (this one? or this one?)

So how do I know, for encoding in our graph, if a project _addresses_ or _is inferred_ (how? by whom?) _to address_ a disorder?

**Comment by anirudh4792** [comment]
In that case,


   - Project addresses disorder

**Comment by anirudh4792** [comment]
For health-lifesci:possibleTreatment
<http://health-lifesci.schema.org/possibleTreatment>, I am not comfortable
using the word treatment or therapy, especially in relation to mental
health (I feel its one of those controversial terms, and could explain
further in person), and there are no therapies or treatments in the db.

Regarding addresses (closest synonym I can think of is deals with,
tackles), I am not able to get an appropriate dictionary/wiki link or other
links, and so gave my own definition - directs attention to an issue with
the intent to improve it.

I am a bit lost on how you are getting these definitions from schema.org or
dcterms. Please let me know when I can drop by at your convenience.

**Comment by shnizzedy** [comment]
> For [health-lifesci:possibleTreatment](http://health-lifesci.schema.org/possibleTreatment), I am not comfortable using the word treatment or therapy, especially in relation to mental health (I feel its one of those controversial terms, and could explain further in person), and there are no therapies or treatments in the db.

Fair enough, although I feel like "addresses", "deals with" and "tackles" all imply solving a problem while "treatment" and "therapy" imply an attempt that may or may not succeed.

I'm less trying to advocate for health-lifesci:possibleTreatment here than trying to say that I think "addresses", "deals with" and "tackles" have at least the same problems as "treatment" and "therapy", perhaps even moreso.

> Regarding addresses (closest synonym I can think of is deals with, tackles), I am not able to get an appropriate dictionary/wiki link or other links, and so gave my own definition - directs attention to an issue with the intent to improve it.

I think this definition is on the right track but I'm not quite satisfied with the wording yet (sorry!).

> directs attention to an issue with the intent to improve it

So a project directs attention to an issue and intends to improve that issue by thus directing that attention? Intuitively I feel like attention is overemphasized in this definition, but maybe I'm off-base. Are these projects all attempts to intervene or are they just informational? Some of each? Other purposes?

---

> I am a bit lost on how you are getting these definitions from schema.org or dcterms. Please let me know when I can drop by at your convenience.

Any time before 6!

**Comment by anirudh4792** [comment]
I agree. Attention and improvement may not be appropriate words to use in
the definition of a relationship between disorder and project. It could be
to define the relationship between project and thing, which we will handle
eventually.

I'm on my way. Thanks.

**Comment by shnizzedy** [comment]
😎 project dcterms:subject disorder
