### ISSUE TITLE
🖇 Project ~ MHealthPeople

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#80]
How does _[02/23 mentalhealthtechnology3 + OCEAN :: Project](https://docs.google.com/spreadsheets/d/1OHtVRqRXvCUuhyavcLSBU9YkiEJfThFKrXHmcg4627M/edit#gid=274240996) :: **project**_ relate to _[02/23 mentalhealthtechnology3 + OCEAN :: Project](https://docs.google.com/spreadsheets/d/1OHtVRqRXvCUuhyavcLSBU9YkiEJfThFKrXHmcg4627M/edit#gid=274240996) :: **MHealthPeople_index**_? In our [structure to keep spreadsheet](https://docs.google.com/spreadsheets/d/1bQmu1emZ_9J1qfrzTi2CgTELME4mRqn74hMwbY9wV-A/edit#gid=1162864977), we have
- project is named person

  or
- person is named project

, either of which I think is incorrect. My intuition is that person is the subject and project is the object.

- Person provides information about project?
- Person created project?
- Person maintains project?
- Person reviewed project?
- Person uses project?
- Person used project?
- Person recommended project?
- Person named project?
- Something else?

**Comment by anirudh4792** [comment]
*MHealthPeople_index is the mental health team/people involved in the
project. *

*eg., for tingle, the MHealthPeople_index would refer to Matter Lab (name
of the Lab) and its members Arno Klein, Jon Clucas...*

*In most cases, if a project (eg app, wearable) had a research publication
associated with it, the authors and their labs became MHealthPeople_index*




* - Person provides information about project? - Nope, but thank you for
giving me this idea, which would be useful during future crowdsourcing-
Person created project? - In most cases, yes- Person maintains project? -
no, but this will be covered in our project evaluation criteria (version
date)- Person reviewed project? - no, will be relevant for future
crowdsourcing- Person uses project?  - Person used project? -- handled
separately through internal_mapping. eg LENA is a project, and this
'project' has been used by a research team, which was another project-
Person recommended project? - future use case- Person named project? - lol
who named mindlogger- Something else? *

**Comment by shnizzedy** [comment]
> [I'm sorry, I didn't mean for you to answer each bullet; those were intended as choose-one options (this one? or this one?)](https://github.com/ChildMindInstitute/mhdb/issues/79#issuecomment-380262274)

So here, if a project has a research publication, the MHealthPeople in the same row on the project sheet are the authors?
If a project has more than one publication, the author linked on the project is an author of all of the publications?
What does it mean to have an author without a publication?

**Comment by anirudh4792** [comment]
At this moment, these considerations are irrelevant and not needed for this
case (i.e., research publications and authors need not come into the
picture)

If a project has an *MHealthPeople_index, it refers to the lab/people
involved in that project. *

**Comment by shnizzedy** [comment]
> At this moment, these considerations are irrelevant and not needed for this case (i.e., research publications and authors need not come into the picture)

Do you mean we have irrelevant columns in some of these workbooks? Or does "at this moment" mean that these columns are relevant but lower priority? As I work through the columns, how do I know which ones to skip and/or come back to?

> If a project has an MHealthPeople_index, it refers to the lab/people involved in that project.

Involved in any capacity?

**Comment by shnizzedy** [comment]
Would project [dcterms:contributor](http://dublincore.org/documents/dcmi-terms/#terms-contributor) person be a fair predicate to use for this relationship?

> Definition: An entity responsible for making contributions to the resource.
Comment: Examples of a Contributor include a person, an organization, or a service.

**Comment by anirudh4792** [comment]
"Do you mean we have irrelevant columns in some of these workbooks?" - *No,
we do not have irrelevant columns in some or any of these workbooks*


*Or does "at this moment" mean that these columns are relevant but lower
priority? - Apologies. The phrase "at this moment" can be forgotten. *







*The only statement that needs to be considered is If a project has
an MHealthPeople_index, it refers to the lab/people involved in that
project. Nothing more, nothing lessAs I work through the columns, how do I
know which ones to skip and/or come back to? - nothing needs to be
skippedInvolved in any capacity? - my preference is to have just  'involved
in'  which refers to involved at some capacity. Would
project dcterms:contributor
<http://dublincore.org/documents/dcmi-terms/#terms-contributor> person be a
fair predicate to use for this relationship? - my preference is to have
just  'involved in' . However, I cannot think of a single instance where
contributor would be incorrect.Hope this clears things*

**Comment by shnizzedy** [comment]
For each relationship, we need a property, and each property needs a definition.

For #76, #74, #75 & #77, I'm finding properties in this order of preference:

1.  Use the property given in [structure_to_keep](https://docs.google.com/spreadsheets/d/1bQmu1emZ_9J1qfrzTi2CgTELME4mRqn74hMwbY9wV-A/edit#gid=1162864977).
If 1. is missing, undefined, or doesn't make sense:
    2.1. If I have confidence that I know the relationship, use the relationship that I suspect.
    2.2. If I am unsure, open a question issue to ask @anirudh4792, the expert who constructed the workbooks.

Since you are the expert regarding the structure of these workbooks, I fully defer to your expertise in defining the relationships, but if the options I give are insufficient, I still need one or more defined predicates to proceed.

---

In this case,
1. should we proceed with contributor in addition to "involved in"?
2. I need an IRI and/or a definition for "involved in" in order to use that property.

**Comment by shnizzedy** [comment]
> *I think we proceed with contributor only* and not have 'involved in' at all, since contributor fits the bill for all entities.

Cool! Will do!

> Does this sound correct - If I cannot find a term with an already existing IRI/definition that accurately defines the relationship and what I am trying to indicate, can we add our own term and give it a definition (create our own IRI?)? eg addresses; synonym - deals with, definition - directs attention to an issue with the intent to improve it

Yep, with a preference towards finding existing IRIs for inferencing power (if we define a property, we can infer over any statements we or others make using that statement; if we use a property already in use elsewhere, we can additionally infer over any already existing statements using that property).

A relevant point of clarification here: we can also specify domains (what classes of subject can do this thing) and/or ranges (what classes of objects can this thing be done to) for properties.

> Do you find existing IRIs in snowmed, schema.org, bioontology etc.?

Yep. schema.org and dcterms are pretty robust but anywhere that has a good definition can do.

**Comment by shnizzedy** [comment]
One other note about definitons: we can take them from elsewhere too. Here's what I'm putting for Wearable:

```ttl
mhdb:Wearable rdfs:subClassOf schema:Product ;
	rdfs:comment """A smart electronic device (electronic device with micro-controller(s)) that can be worn on the body as implants or accessories."""@en ;
	rdfs:isDefinedBy <https://en.wikipedia.org/wiki/Wearable_technology> ;
	rdfs:label """Wearable"""@en .
```

**Comment by anirudh4792** [comment]
resolved and deleted - no 199 for goliah.  must have crept in when I was
ctrl+f'ing for 199 sometime in the past. Thanks
