### ISSUE TITLE
📖 TypeOfProject Definitions

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mhdb#81]
I (think I) have a good grasp on the types not listed here, but @anirudh4792, can you define the following project types?

- resource
- digital/online tool
- a combination of a social narrative and gaming system
- individual - effort towards mental health
- news feature
- intervention program
- center
- research center
- environment

For "a combination of a social narrative and gaming system", please define "social narrative" and "gaming system".

Does "news feature" include any particular media? Newspaper? Magazine? Journal? Radio? TV? Blog? Direct mail?

Is "research center" a subclass of "center"?

**Comment by anirudh4792** [comment]
Thank you for finding these


   - resource - renamed to resource guide
   - digital/online tool - renamed to digital tool
   - center - exists as it is

The rest have been deleted, and no longer exist in the DB. So that should
answer your questions

**Comment by shnizzedy** [comment]
> - resource - renamed to resource guide

Got it.

I still need clarification on these though:

> - digital/online tool - renamed to digital tool
> - center - exists as it is

What are they?

**Comment by anirudh4792** [comment]
center - deleted and not there in the db anymore (only one project indexed
to 'center' and the project was already present as a mhealth team)
digital tool -  For projects involving interactive digital boards; slowing
down speed of the video; social story authoring tool; tablet-based activity
schedule etc.; I coudnt come up with a better general term than digital
tools. Any suggestions?

**Comment by shnizzedy** [comment]
> center - deleted and not there in the db anymore (only one project indexed to 'center' and the project was already present as a mhealth team)

Since I'm going column-by-column, I'm probably just not there yet, but how is a project encoded as being an mhealth team?

> digital tool - For projects involving interactive digital boards; slowing down speed of the video; social story authoring tool; tablet-based activity schedule etc.; I coudnt come up with a better general term than digital tools. Any suggestions?

For all of these (for any entity or property, really) as long as we have a good definition, I don't care what the term is. Are these digital tools all software? Are they somehow more specific than [schema:SoftwareApplication](http://schema.org/SoftwareApplication)?

> A software application.

By the way, I'm currently using schema:SoftwareApplication for app. Appropriate?

**Comment by anirudh4792** [comment]
"Since I'm going column-by-column, I'm probably just not there yet, but how
is a project encoded as being an mhealth team?" - For OCEAN, long back, I
had aggregated information on projects, research centers etc. and while
importing all those entities, I accidentally added a lab as an entry under
projects -  '*projects* done by this lab', and hence the error. I have
cleaned a lot of such errors, repetitions etc., but some may still have
crept in due to the sheer number of rows and columns. My apologies.

"they somehow more specific than schema:SoftwareApplication
<http://schema.org/SoftwareApplication>?" - Nope, software application fits
the bill for all projects under digital tools. Thanks. It is a better fit
than tools(http://schema.org/tool) or anything else.

**Comment by shnizzedy** [comment]
> "Since I'm going column-by-column, I'm probably just not there yet, but how
is a project encoded as being an mhealth team?" - For OCEAN, long back, I
had aggregated information on projects, research centers etc. and while
importing all those entities, I accidentally added a lab as an entry under
projects -  '*projects* done by this lab', and hence the error. I have
cleaned a lot of such errors, repetitions etc., but some may still have
crept in due to the sheer number of rows and columns. My apologies.

So I'm clear, what I'm confused about (where "a lab as an entry under
projects -  '*projects* done by this lab'" is in these workbooks) _was_ in the workbooks somewhere but _no longer is_?

> "they somehow more specific than schema:SoftwareApplication
<http://schema.org/SoftwareApplication>?" - Nope, software application fits
the bill for all projects under digital tools. Thanks. It is a better fit
than tools(http://schema.org/tool) or anything else.

Cool. Does anything differentiate app from digital tool?

**Comment by shnizzedy** [comment]
Does '[schema:PresentationDigitalDocument](http://schema.org/PresentationDigitalDocument)' make sense for 'presentation'?

> A file containing slides or used for a presentation.

The way I think it might not work is if any of the presentations are something like a live seminar as opposed to a slide deck or a video.

**Comment by binarybottle** [comment]
If the live seminar uses slides, then the file with slides seems in line, and any recording of the presentation seems fine as well.  The only problem is whether to consider the live stream itself to be a "file"...

**Comment by anirudh4792** [comment]
Yes. Makes sense to me.

**Comment by shnizzedy** [comment]
> If the live seminar uses slides, then the file with slides seems in line, and any recording of the presentation seems fine as well. The only problem is whether to consider the live stream itself to be a "file"...

Agreed. The question is whether any live streams or such non-file presentations are mapped to "presentation" on the TypeOfProject sheet. Based on ["Yes. Makes sense to me."](https://github.com/ChildMindInstitute/mhdb/issues/81#issuecomment-383178201), I think the answer is that everything pointing to that cell is a PresentationDigitalDocument.

**Comment by shnizzedy** [comment]
Is a 'gaming system' distinct from a [schema:Game](http://schema.org/Game)? If so, how?

> The Game type represents things which are games. These are typically rule-governed recreational activities, e.g. role-playing games in which players assume the role of characters in a fictional setting.

**Comment by shnizzedy** [comment]
Also, please define "individual - effort towards mental health"

**Comment by anirudh4792** [comment]
"individual - effort towards mental health" has been deleted and no longer
exists in the db

**Comment by anirudh4792** [comment]
'gaming system' was cleaned and doesnt exist in the db as well

On Fri, Apr 20, 2018 at 4:48 PM, Anirudh Krishnakumar <anirudh4792@gmail.com

**Comment by shnizzedy** [comment]
Ah. Thanks.  In that case, I'm abandoning my plan to work from a frozen version and switching to the live to avoid wasting time defining things we're no longer using.

**Comment by anirudh4792** [comment]
Actually, except for type of projects (the doubtful ones are probably
exhausted), keywords, and Rs in neutral behaviors, nothing else has
changed. It could be worth considering for convenience if you would want to
continue with the frozen one
